### ISSUE TITLE
释放lowpriority 如果休息完毕

### ISSUE THREAD

**Issue by Shawnsdaddy** [ArkMowers/arknights-mower#165]
目前lowe priority 组如果休息好了，还是会占着一个宿舍位置，不利于有效利用宿舍。

除去工作以及宿舍休息，干员需要第三状态，**休息完毕**

低优先级休息组休息完毕时，可以释放宿舍位给其他需要休息的干员。

同时纠错应该跳过

**Comment by Shawnsdaddy** [comment]
252宿舍休息需要优化，理想最终状态是：
内置动态的规划（根据宿舍整体心情让最大分组数在4-8之间自动切换）

改动第一阶段： 
    释放low_prioirty 如果该干员休息完毕.

**Comment by Shawnsdaddy** [comment]
1. 低优先级也会录出宿舍时间, 有人休息的时候可以debug检查一下self.op_data.dorm，确保低优先的出宿舍时间被记录

2. 在安排人进宿舍的时候，可以加上逻辑判定，[available_free](https://github.com/ArkMowers/arknights-mower/blob/dev_shawn/arknights_mower/utils/operators.py#L273) 这个方程会在生成进宿舍排班表的时候被调用。会返回当前宿舍剩余的空闲个数。。如果当前的房间有人可是出宿舍时间超过当前时间的话，则需要计数（目前是不会检查出宿舍时间的）。
修改这一步以后，就会释放低优先的宿舍位来安排其他干员了。

3. 释放出的低优先宿舍位，还需要去纠错方程里确保其他未休息完毕的干员不会被纠错任务带出宿舍。[not_valid](https://github.com/ArkMowers/arknights-mower/blob/dev_shawn/arknights_mower/solvers/base_schedule.py#L494)

**Comment by Shawnsdaddy** [comment]
移除宿舍的心情满干员的房间自动会被设置空值，心情也可以设置成24，这样就是issue里提到的休息完毕的这状态了。
这样就可以充分利用宿舍位置

**Comment by ZhaoZuohong** [comment]
想到可以顺便改进的地方：252最大组人数大于吃单回的位置，宿舍有些干员心情回满后，单回技能会转移到其他干员上，回满时可以趁机重新读时间。

**Comment by Shawnsdaddy** [comment]
该功能已经实装

**Comment by ZhaoZuohong** [comment]
有没有加释放白名单，防止某些干员被踢出基建

**Comment by Shawnsdaddy** [comment]
> 有没有加释放白名单，防止某些干员被踢出基建

好好
