### ISSUE TITLE
新版 LowerLimit 配置项失效

### ISSUE THREAD

**Issue by fearlessxjdx** [ArkMowers/arknights-mower#201]
设置了 LowerLimit 后，干员还是会在心情小于 50% 时休息，不会工作到 LowerLimit 设定值。

**Comment by Shawnsdaddy** [comment]
Lower_limit 并不是指心情阈值，，而是应对卡心情的干员。比如说，夕，令。等等。

如果想让心情阈值低于某个值，可以修改[休息阈值](https://github.com/ArkMowers/arknights-mower/blob/dev_shawn/diy.py#L66)

然而并不推荐这么做。因为延后休息并不会提升公休比

工作24小时，休息4小时和工作12小时，休息2小时本质是一样的
