### ISSUE TITLE
载入黑名单以后不进行下一步,3.3.2更新的标题显示地址也和填写的不一样

### ISSUE THREAD

**Issue by emmmmmmmmmmmmmmmmmmmmmmmmmmm** [ArkMowers/arknights-mower#204]
![SL@8{$ 7)NMM$Y@U6Q_5 39](https://github.com/ArkMowers/arknights-mower/assets/136322322/5a029deb-6121-4839-a56a-2fc144a17312)
[mower.zip](https://github.com/ArkMowers/arknights-mower/files/11721038/mower.zip)

**Comment by ZhaoZuohong** [comment]
Mower的GUI是个网页，标题的地址是Mower后端的地址，不是adb的地址。

不进行下一步可能与宿舍有关。
