### ISSUE TITLE
index 1920 is out of bounds for axis 1 with size 1920

### ISSUE THREAD

**Issue by ZhaoZuohong** [ArkMowers/arknights-mower#211]
https://github.com/ArkMowers/arknights-mower/blob/9c5514beea5c89f5dd7033cffc689ebe4239966e/arknights_mower/utils/character_recognize.py#L144

这里有时会报错 `IndexError: index 1920 is out of bounds for axis 1 with size 1920`。

或许是截图的问题？

**Comment by Shawnsdaddy** [comment]
据说是截图多截 了1个pixel 不知道咋截的
