### ISSUE TITLE
烟火/感知模式下同组干员的LowerLimit

### ISSUE THREAD

**Issue by ZhaoZuohong** [ArkMowers/arknights-mower#218]
目前设置烟火/感知模式后，仅为琴柳与重岳设置了 `LowerLimit`：

https://github.com/ArkMowers/arknights-mower/blob/5dad8d1e07b3c98c60585cf36ad6ff40212f1dc5/arknights_mower/__main__.py#L37-L46

这会导致除琴柳与重岳以外令夕同组的干员趋向于在心情区间 $[0, 12]$ 内工作，看起来非常怪异。

能否将排班表中与令夕同组干员的 `LowerLimit` 都设置为 12？

**Comment by Shawnsdaddy** [comment]
当时偷懒了，其实应该是设同组的
