### ISSUE TITLE
最新测试版，运行一晚上就崩，4次了，麻烦看下

### ISSUE THREAD

**Issue by fearlessxjdx** [ArkMowers/arknights-mower#219]
最后在这个页面无限循环，而且必须重启模拟器才能再次运行diy.py。
![sunlogin_20230710080118](https://github.com/ArkMowers/arknights-mower/assets/17431574/76a4d4be-ce9d-4361-91e1-e04d6f14122f)

日志在这：
[runtime.log](https://github.com/ArkMowers/arknights-mower/files/11996581/runtime.log)

**Comment by ZhaoZuohong** [comment]
或许是截图的问题，换个模拟器试试？

**Comment by Shawnsdaddy** [comment]
实装了重启模拟器功能，，试试
