### ISSUE TITLE
插拔问题

### ISSUE THREAD

**Issue by ZhaoZuohong** [ArkMowers/arknights-mower#229]
1. 换班任务挤掉了跑单
日志：[runtime.log](https://github.com/ArkMowers/arknights-mower/files/12123217/runtime.24.log)

18:41分开始的长任务持续太久，导致错过了跑单。

2. 宿舍未满员读取时间

4. 非贸易站干员上下班影响贸易站效率

**Comment by ZhaoZuohong** [comment]
![image](https://github.com/ArkMowers/arknights-mower/assets/34163622/6b571df9-6023-4a52-ab7c-1ebd66b37c4f)

[排班表.json.zip](https://github.com/ArkMowers/arknights-mower/files/12123254/252.3.json.zip)

**Comment by ZhaoZuohong** [comment]
或许把长任务拆分成一些短任务（或者避免合并）会有帮助？

**Comment by Shawnsdaddy** [comment]
SchedulerTask(time='2023-09-19 09:41:17.215035',task_plan={'room_1_2': ['Current', '黑键', '巫恋'], 'room_1_1': ['Current', '迷迭香', 'Current']},task_type=TaskTypes.NOT_SPECIFIC,meta_data='dorm0,dorm1,dorm2')||SchedulerTask(time='2023-09-19 09:48:26.508688',task_plan={'room_3_1': ['Current', '但书', '龙舌兰']},task_type=TaskTypes.RUN_ORDER,meta_data='room_3_1')||S
chedulerTask(time='2023-09-19 09:48:47.141305',task_plan={},task_type=TaskTypes.FIAMMETTA,meta_data='')||SchedulerTask(time='2023-09-19 09:50:04.693325',task_plan={'room_1_2': ['Current', '龙舌兰', '但书']},task_type=TaskTypes.RUN_ORDER,meta_data='room_1_2')



所有任务挤在一起导致漏单

**Comment by ZhaoZuohong** [comment]
快速葛朗台

https://github.com/ArkMowers/arknights-mower/assets/34163622/960c5cca-09ed-4b2c-a986-cf1a389b5b34

**Comment by Shawnsdaddy** [comment]
@ZhaoZuohong 没问题就close了咯:)
