### ISSUE TITLE
记录公休比以及基建产出数据

### ISSUE THREAD

**Issue by Shawnsdaddy** [ArkMowers/arknights-mower#242]

**Comment by Shawnsdaddy** [comment]
建议可以生成一个本地Excel文件，包含日期等其他信息

**Comment by Shawnsdaddy** [comment]
建议在[Operator](https://github.com/ArkMowers/arknights-mower/blob/dev_shawn/arknights_mower/utils/operators.py#L352)里新增几个个字段(总休息时间(total_resting)，总工作时间(total_working)，上次切换时间(last_status_change)）
统计应该从第一次出宿舍开始计算（第一次出宿舍以后，last_status_change从None变更为当前时间戳）

[移除宿舍时会触发](https://github.com/ArkMowers/arknights-mower/blob/dev_shawn/arknights_mower/utils/operators.py#L185)
可以新增条件判定是否为从工作站移入宿舍
（然后就是减去last_status_change来计入总休息时间和工作时间了）

**Comment by ZhaoZuohong** [comment]
我觉得可以保存到数据库里，不然重启mower就没了
