### ISSUE TITLE
贸易站的进宿舍休息 有时候跑单的时候会把宿舍的换进去

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#245]
贸易站的进宿舍休息之后 如果跑单的时候卡了 导致识别失败 之后会把本来在宿舍休息的干员换进贸易站，导致夜刀还在休息 调查团却去贸易战上班了
[runtime跑单bug.log](https://github.com/ArkMowers/arknights-mower/files/12331391/runtime.bug.log)
![QQ图片20230814115537](https://github.com/ArkMowers/arknights-mower/assets/137869765/7a2ca871-9189-439a-8cf7-2e3b443dee7e)

**Comment by Shawnsdaddy** [comment]
生成的纠错任务是一个组全上的，不会存在单上一个人的情况
![image](https://github.com/ArkMowers/arknights-mower/assets/33809511/ddcb926d-8e26-4db3-baa9-9cb2f16772f4)

**Comment by czt635** [comment]
> 

不是纠错任务过程中替换的
举个例子，夜刃和调查团去休息，换上了替补组，过了一段时间开始跑单，跑单过程中卡了，重新开始跑单，换上但书龙舌兰跑单后 是用调查团替换但书龙舌兰 而不是用替补组替换他们，我截图不全，后面有具体过程，你可以看一下我发的log

**Comment by czt635** [comment]
感觉是孑的纠错任务有问题·
![image](https://github.com/ArkMowers/arknights-mower/assets/137869765/840f5d19-834b-4df1-a8aa-9d32325a66ce)
还是看一下完整log吧 我也不是很懂

**Comment by czt635** [comment]
> 生成的纠错任务是一个组全上的，不会存在单上一个人的情况 ![image](https://user-images.githubusercontent.com/33809511/260381083-ddcb926d-8e26-4db3-baa9-9cb2f16772f4.png)

感觉是孑的纠错任务有问题，我也不是很懂，你最好看一下完整的log
![image](https://github.com/ArkMowers/arknights-mower/assets/137869765/534682b7-7801-40e1-8527-012c05c2278c)
