### ISSUE TITLE
见行者红脸了也没有换下，替换组里明明有满心情的干员

### ISSUE THREAD

**Issue by YuZeah** [ArkMowers/arknights-mower#247]
见行者经常红脸了也在工作，原本我以为是不是见行者心情消耗太快，mower“以为”见行者还没红脸，直到我重新开始执行了一次，mower明明截到了见行者，mood：0.0，然后mower就接入了MAA（？？？）。之前泡普卡也常常红脸工作，后来我大改了一次排班表之后好像就没出现过了，有一次更是打开一看，十几二十个红脸，我重新执行了，mower就把其他红脸都换下了，唯独让见行者红脸工作。之前几个版本都是差不多的排班表，后来更新到好像v3.4.2（？不确定）就会经常见行者红脸工作（之前是泡普卡，当时情况是制造站明明替换组有干员满心情，mower依然坚持让高效组干员（主要是泡普卡）红脸工作）
[runtime.log](https://github.com/ArkMowers/arknights-mower/files/12342729/runtime.log)

**Comment by Shawnsdaddy** [comment]
换下也是得有位置的，建议吧心情阈值拉高，对于见行者这种心情消耗过快的比较友好

**Comment by Shawnsdaddy** [comment]
如果许多干员心情过低， 则会每次轮替只休息半个小时，直到慢慢回复满

**Comment by YuZeah** [comment]
宿舍没位置也能先换上满心情的替换干员吧，否则一直挂着红脸干员不是白白亏效率吗？

**Comment by YuZeah** [comment]
宿舍没位置也能先换上满心情的替换干员吧，否则一直挂着红脸干员不是白白亏效率吗？

**Comment by Shawnsdaddy** [comment]
> 宿舍没位置也能先换上满心情的替换干员吧，否则一直挂着红脸干员不是白白亏效率吗？

设计是 24小时运行的，一般不会出现你这种情况。
