### ISSUE TITLE
慕斯与休谟斯识别

### ISSUE THREAD

**Issue by ZhaoZuohong** [ArkMowers/arknights-mower#268]
检测到的干员休谟斯,需要安排的干员慕斯

[慕斯休谟斯.log](https://github.com/ArkMowers/arknights-mower/files/12513861/default.log)

**Comment by Shawnsdaddy** [comment]
我觉得简单一点加个OCR试试？

**Comment by ZhaoZuohong** [comment]
它直接识别成慕斯了，不会走ocr.json
