### ISSUE TITLE
Request to Change License from MIT to AGPL

### ISSUE THREAD

**Issue by ChingCdesu** [ArkMowers/arknights-mower#277]
Due to your violation against AGPL, we, the developers of MAA Arknights Assistant, request you to change your license from MIT to AGPL within 30 days, otherwise we will initiate a DMCA request.

Reasons for the Change:
1. Copyleft and Source Code Availability: The AGPL is a strong copyleft license that ensures the availability of the source code for any modifications or enhancements made to the software. This aligns with our commitment to open-source principles and encourages collaboration within the community. The code in file https://github.com/ArkMowers/arknights-mower/blob/main/arknights_mower/utils/asst.py is same as https://github.com/MaaAssistantArknights/MaaAssistantArknights/blob/main/src/Python/asst/asst.py which is protected by AGPL.

Implementation Plan(Not both required):
1. Deletion or modification of code that violate the AGPL agreement.
2. Update the repository's license file and documentation to reflect the change from the MIT License to the AGPL.

**Comment by ZhaoZuohong** [comment]
文档里要改哪一部分？

**Comment by ChingCdesu** [comment]
将License更改为AGPL

**Comment by ZhaoZuohong** [comment]
你不是说要update documentation to reflect the change嘛，文档在这儿：https://arkmowers.github.io/arknights-mower/，你看要怎么update？

**Comment by ChingCdesu** [comment]
如果文档内没有License的相关声明，那就不用

**Comment by ZhaoZuohong** [comment]
好滴好滴

**Comment by Konano** [comment]
To address this issue, we will no longer use the MAA Arknights Assistant sample files directly and will rewrite the code that interacts with MAA Arknights Assistant.

By the way, we don't feel that this file needs to be covered by the AGPL. You can add other protocols (e.g. Apache 2.0) to all the sample files.

**Comment by ChingCdesu** [comment]
Completed in 1ac78c7
