### ISSUE TITLE
释放FREE位 导致纠错 导致提前回去上班

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#283]
稀音 K200 红云 组，K200与红云回满后 会释放FREE位 导致其他需休息组把红云 K200换下 产生纠错任务 导致稀音没回满心情就去上班
9-13 6：40
[runtime(4).log](https://github.com/ArkMowers/arknights-mower/files/12591650/runtime.4.log)

**Comment by czt635** [comment]
其他如 麒麟夜刃组应该也有相同问题 无log

**Comment by czt635** [comment]
首层发的log还有一个bug 已经设置了麒麟R夜刃需回满心情，但是却产生了一个9-13 7:50让麒麟夜刃回去上班的任务，但是实际上这个时间麒麟夜刃并未回满心情，只有黑龙和调差团在这个时间刚好回满心情

**Comment by Shawnsdaddy** [comment]
应该修，，修了。。

**Comment by Shawnsdaddy** [comment]
问问E佬 @ZhaoZuohong

**Comment by czt635** [comment]
9.20 最新版还没有修
![QQ截图20230921130327](https://github.com/ArkMowers/arknights-mower/assets/137869765/41c586b5-02a9-42d6-a305-480357475e03)
[runtime.log](https://github.com/ArkMowers/arknights-mower/files/12695692/runtime.log)

**Comment by Shawnsdaddy** [comment]
明白了，应该是清除的时候只重设了心情并没有重设心情掉率和时间

**Comment by Shawnsdaddy** [comment]
153的宿舍效能差得不是特别明显所以没发现
