### ISSUE TITLE
低优先级干员抢VIP位单回

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#285]
假设一个宿舍既有VIP 又有低优先干员，VIP已回满 低优先未回满 此时换上新VIP位干员，单回会是低优先干员吃。建议软件加一道检测，如果换新VIP干员时，宿舍内有未回满心情低优先干员，则先将低优先干员T出宿舍 再放进VIP干员和低优先干员（根据单回索敌机制，单回会给到VIP干员）

**Comment by Shawnsdaddy** [comment]
这个是不会的，除非新换上的VIP是断罪者， 琴柳这类的，你试试？

**Comment by czt635** [comment]
我手动试过了 是有这个问题的
是用安比尔（群回）蜜莓（单回） 龙舌兰（VIP1 心情马上就满了） 异客（低优先）红豆（VIP2）手动测试的
先安排 安比尔 蜜莓 龙舌兰 异客 此时单回在龙舌兰
然后等龙舌兰回满心情 回满心情后单回给到了异客
然后再用红豆替换龙舌兰（干员顺序不变 为安比尔 蜜莓 红豆 异客； 且群回、单回、异客始终没有离开宿舍 与mower换班相同操作） 单回还是在异客

**Comment by Shawnsdaddy** [comment]
![image](https://github.com/ArkMowers/arknights-mower/assets/33809511/f91c8652-5543-41c3-a0d9-cab43c09ab5a)

**Comment by Shawnsdaddy** [comment]
![image](https://github.com/ArkMowers/arknights-mower/assets/33809511/08ea8cf9-49f7-4f97-9895-0ab7ddcfd1bc)

**Comment by Shawnsdaddy** [comment]
umm 好像是有这个问题，我也试了一下

**Comment by czt635** [comment]
对啊 单回还是给到杜宾 没给苍苔

**Comment by ZhaoZuohong** [comment]
修复没有任何作用

**Comment by ZhaoZuohong** [comment]
最大组人数必须写4
