### ISSUE TITLE
不消耗无人机下 加速贸易站单站不会持续加速

### ISSUE THREAD

**Issue by Fuynkio** [ArkMowers/arknights-mower#299]
无人机加速贸易站单站（搓玉，指定贸易站），并不会使用无人机至 **无人机使用阈值** 以下 ,而是**加速一次**。（猜测）
```
9月19日 16:58:58 无人机190 
9月19日 19:53:53 无人机159 
9月19日 20:44:51 无人机174
9月19日 22:02:29 无人机121
```
截图：
[0919-run_order.zip](https://github.com/ArkMowers/arknights-mower/files/12668527/0919-run_order.zip)
log:
[runtime.log.zip](https://github.com/ArkMowers/arknights-mower/files/12668570/runtime.log.zip)
排班表:
[跑单-243-1书2金1玉.zip](https://github.com/ArkMowers/arknights-mower/files/12668615/-243-1.2.1.zip)
conf.yml:
```
无人机阈值：120 
无人机使用房间：指定room_3_2
```

另 既然不消耗无人机来加速订单了,那无人机就可以随时加速订单/产物了，所以可以把推荐阈值改成0或者80（搓芯片）？

**Comment by Shawnsdaddy** [comment]
不需要指定贸易站，跑单自动加速贸易站
