### ISSUE TITLE
关于需要用尽心情干员的建议

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#304]
需要用尽心情干员目前会因为替换组被占用或者宿舍低优先位置满员而导致0心情时不进宿舍休息，导致效率亏损，建议出现替换组占用或低优先位置满员时能清空宿舍，让0心情干员优先休息。现在低优先位置满员是没有邮件提醒的 ，替换组被占用虽然有邮件提醒，但是在凌晨也没办法查看邮件
![image](https://github.com/ArkMowers/arknights-mower/assets/137869765/f6072fbe-6ada-42c1-b046-f8db93d22692)

**Comment by Shawnsdaddy** [comment]
强制替换也可以，最好加个开关？？

最好的办法就是替换组安排多一个保险？？

**Comment by czt635** [comment]
还是强制替换比较好 替换组多安排一个也会亏效率（替换组2效率低于替换组1） 而且多一个替换组遇到宿舍低优先位满员的情况还是会取消拉普兰德进宿舍
加个开关是啥？

**Comment by Shawnsdaddy** [comment]
@czt635 改成了提前执行，如果被占用，这样不会亏效率了。

**Comment by czt635** [comment]
不是很明白 提前执行 如果被占用 还是不会进宿舍 而且任务也会被删除 不是还是会亏效率吗？

**Comment by Shawnsdaddy** [comment]
比如说替换组被占用了，就把被占用的替换组的主力提前上班，这样替换组就有空余给用尽组了
