### ISSUE TITLE
铅踝 用尽问题

### ISSUE THREAD

**Issue by Shawnsdaddy** [ArkMowers/arknights-mower#317]

**Comment by Shawnsdaddy** [comment]
好像还是有点问题？

**Comment by ZhaoZuohong** [comment]
![image](https://github.com/ArkMowers/arknights-mower/assets/34163622/398e4e14-e2c7-48ce-8cce-ac69272ac91c)
感觉铅踝不用设置用尽也行，我的心情阈值是 65%，铅踝有时候比较接近 8 点心情才会休息

**Comment by ghzh21th** [comment]
方便问下，铅踝是有内置方案吗

> ![image](https://private-user-images.githubusercontent.com/34163622/294527240-398e4e14-e2c7-48ce-8cce-ac69272ac91c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDM4ODMsIm5iZiI6MTcwOTY0MzU4MywicGF0aCI6Ii8zNDE2MzYyMi8yOTQ1MjcyNDAtMzk4ZTRlMTQtZTJjNy00OGNlLThjY2UtYWM2OTI3MmFjOTFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEyNTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxNGIwMDliZTA4ZmM2ZjYxZGEzYzg4MjJlMTBlZWE3ZWYwMjUzMWE5N2NmMjk4YjBiM2U2MDA2ZDk4YjZmOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7op9tb3yxez9hTxeiMSL8BkDYD3zOLDFSaN6CesX77s) 感觉铅踝不用设置用尽也行，我的心情阈值是 65%，铅踝有时候比较接近 8 点心情才会休息

**Comment by ZhaoZuohong** [comment]
> 铅踝是有内置方案吗

@ghzh21th 

https://github.com/ArkMowers/arknights-mower/blob/47e3f47a8c01dd54be67cbff3773999d604678d4/arknights_mower/utils/operators.py#L237-L249

搭配红云做主力时需要写副表，可以参考我正在用的排班表：

![31贸2赤金抽象裁缝](https://github.com/ArkMowers/arknights-mower/assets/34163622/0de0a90f-6bfa-4ffa-8a2e-f6fd3a304c5d)
