### ISSUE TITLE
稀音大小姐未回满心情就回去上班

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#348]
稀音大小姐心情未满 其他人满了就回去上班了 设置了稀音需回满心情
![image](https://github.com/ArkMowers/arknights-mower/assets/137869765/57cff15b-1159-453b-9470-3147fa8e94ba)
[runtime(1).log](https://github.com/ArkMowers/arknights-mower/files/12923391/runtime.1.log)
[runtime (2).log](https://github.com/ArkMowers/arknights-mower/files/12923392/runtime.2.log)
![image](https://github.com/ArkMowers/arknights-mower/assets/137869765/19eb9151-3fdc-46d7-8a5f-2a7b87b3f053)
![image](https://github.com/ArkMowers/arknights-mower/assets/137869765/b3752f6a-5170-4a90-ade7-74cd2f149ba6)

**Comment by Shawnsdaddy** [comment]
红云帕拉斯得设置成低优先级，不然到了24 就会把其他组员带上班。
详情请参考： [动态换班上班逻辑](https://arkmowers.github.io/arknights-mower/conf/5.buildinSettings.html#%E5%8A%A8%E6%80%81%E6%8D%A2%E7%8F%AD%E4%B8%8A%E7%8F%AD%E9%80%BB%E8%BE%91)
