### ISSUE TITLE
未知原因触发；是否退出游戏界面识别成B 服登录界面（alpha13）

### ISSUE THREAD

**Issue by 184812** [ArkMowers/arknights-mower#351]
错误识别截图码109和-1
<img width="901" alt="{C5D77E94-98C5-4933-B541-3032899E3219}" src="https://github.com/ArkMowers/arknights-mower/assets/143787234/c6bdf041-dbb7-4617-897a-66db02fefd9a">
触发频率：半天一次
希望增加对该界面的识别，以不至于循环识别该界面导致的运行暂停

**Comment by Shawnsdaddy** [comment]
识别这块我不是很擅长，要是修的话你可以QQ私我一下B服账号
