### ISSUE TITLE
雷神模拟器 手动重启失效 得重启电脑 尚未支持重启/自动启动

### ISSUE THREAD

**Issue by qwuae1** [ArkMowers/arknights-mower#362]
有的时候会卡住，停止后重新开始执行会提示 尚未支持重启/自动启动
只能重启电脑吗？
关闭模拟器和软件，重启都没用。。。
这是什么原因
没读取到ADB？还是为啥断开了

雷神模拟器

手动重启了模拟器，
好像软件没有识别到。。。非要重启电脑才行。。。
![image](https://github.com/ArkMowers/arknights-mower/assets/36930393/506ac776-d89c-4670-854b-7cda08a62611)

**Comment by Shawnsdaddy** [comment]
查下LOG，如果手动重启无法使用的话，是不是adbserver没重启？

**Comment by ZhaoZuohong** [comment]
怎么安装的
