### ISSUE TITLE
偶现心情读取异常

### ISSUE THREAD

**Issue by Snow-dash** [ArkMowers/arknights-mower#390]
[runtime.log](https://github.com/ArkMowers/arknights-mower/files/13336255/runtime.log)

日志在31335行附近，本来三人的心情应该都19左右，结果都读成9。

不清楚是否是电脑卡顿。

![2)](https://github.com/ArkMowers/arknights-mower/assets/62183802/b67abfd1-8edc-45e7-b3c9-5df484ae5692)
可以看到自动化组三人出现突变。
没有找到对应截图。

**Comment by ZhaoZuohong** [comment]
https://github.com/ArkMowers/arknights-mower/commit/e48d05106d15447c392b275728fac565d83c5e45

心情读取的识别改了，遇到再说
