### ISSUE TITLE
读取剩余时间时遇到红脸干员

### ISSUE THREAD

**Issue by ZhaoZuohong** [ArkMowers/arknights-mower#406]
[runtime (1).log](https://github.com/ArkMowers/arknights-mower/files/13420534/runtime.1.log)
![image](https://github.com/ArkMowers/arknights-mower/assets/34163622/e505be4a-d640-4ae7-a11b-820e4e6b04c1)

**Comment by Shawnsdaddy** [comment]
这个应该解决了？
