### ISSUE TITLE
识别出错，基建代办变成反馈神经，反复循环

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#415]
![image](https://github.com/ArkMowers/arknights-mower/assets/137869765/e62d0c1c-f558-4205-858e-0f2ea3223615)
[runtime.log](https://github.com/ArkMowers/arknights-mower/files/13445283/runtime.log)
![20231123075105](https://github.com/ArkMowers/arknights-mower/assets/137869765/2d515029-1818-49b3-8a8b-86525470381a)

**Comment by czt635** [comment]
首层是202里面的图片 这个是9里面的图片
![20231123075037](https://github.com/ArkMowers/arknights-mower/assets/137869765/37e2f361-8297-4248-b7d9-6aeeb8acb7bf)

**Comment by ZhaoZuohong** [comment]
你运行的是哪个版本？

**Comment by ZhaoZuohong** [comment]
![todo](https://github.com/ArkMowers/arknights-mower/assets/34163622/39f5414b-e5f9-45c4-9b98-8ce56c123e69)

发现 `find()` 会认为在这个区域匹配到了图片。

在 commit 920a7b76ed35da50ef5342214f3ecfd7939a77e2 中，较为精细地限制了识别范围，同时将阈值恢复至 0.15。

在本地使用 Scene 801、208、205、202、1、9 场景下共数千张截图试验，暂未发现误报。

**Comment by ZhaoZuohong** [comment]
![image](https://github.com/ArkMowers/arknights-mower/assets/34163622/f5352cae-35f9-457b-a3c1-1881b01a8b1a)

群友报告葛朗台跑单的等待场景会被识别成 Connecting，`find`()` 认为在这个区域中匹配到了图片。

在 commit 22f81dfb0dc83a205c6c6a8998c06bed8a1781e2 中，限制了匹配结果的最小宽度为 300 像素，在本地使用 run_order 场景下一千张截图试验，暂未发现误报。

**Comment by czt635** [comment]
问题已解决
