### ISSUE TITLE
焰尾和焰影苇草的识别错误

### ISSUE THREAD

**Issue by EightyDollars** [ArkMowers/arknights-mower#428]
排班表中无苇草，但是实际安排时会将焰尾的位置安排上苇草，并一直纠错
![image](https://github.com/ArkMowers/arknights-mower/assets/81128280/8f9e41f9-fa12-4291-95c4-52ab74b9824e)
[焰尾.log](https://github.com/ArkMowers/arknights-mower/files/13546148/default.log)

**Comment by ZhaoZuohong** [comment]
识别从 OCR 改成 KNN 分类了，应该不会再发生了
