### ISSUE TITLE
副表建议

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#439]
建议按副表进宿舍休息后，增加一道读取宿舍回满心情时间的工作，以免回满心情后没有立刻按主表回去上班

**Comment by Shawnsdaddy** [comment]
> 建议按副表进宿舍休息后，增加一道读取宿舍回满心情时间的工作，以免回满心情后没有立刻按主表回去上班

现在主表休息如果触发附表的话，会先生成主表返回休息再切换副表的。

不太清楚您的意思

**Comment by czt635** [comment]
比如孑拉德组，设置孑-德>4,德进宿舍，刚好孑心情是满的，德心情20，德进宿舍后，没有读取德回满心情时间，德进宿舍后不到一小时心情就满了，满心情还是待在宿舍
虽然这个问题可以通过设置德<16等方式解决，但是加个德进宿舍后，读取德回满心情时间的功能会不会比较好？

**Comment by Shawnsdaddy** [comment]
> 比如孑拉德组，设置孑-德>4,德进宿舍，刚好孑心情是满的，德心情20，德进宿舍后，没有读取德回满心情时间，德进宿舍后不到一小时心情就满了，满心情还是待在宿舍 虽然这个问题可以通过设置德<16等方式解决，但是加个德进宿舍后，读取德回满心情时间的功能会不会比较好？

你这个进宿舍是怎么实现的？

**Comment by czt635** [comment]
之前通过编辑任务实现的进宿舍
现在通过不设置编制任务 只是在附表设置只有拉德在一组解决这个问题了 
这个问题可以关闭了
