### ISSUE TITLE
稀音心情未满回去工作

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#443]
[runtime.log](https://github.com/ArkMowers/arknights-mower/files/13698984/runtime.log)
12.17日 13.40左右 稀音心情未满回去工作，猜测是为了空出宿舍给心情快用尽的德克萨斯？

**Comment by Shawnsdaddy** [comment]
https://github.com/ArkMowers/arknights-mower/commit/95ca37a1d98ffdb235810b6cb0c645865f921aa9

这份Log无法显示具体的任务信息，，无法判断是否和我情况相同

**Comment by Shawnsdaddy** [comment]
@czt635  先关闭了如果还有问题再重开
