### ISSUE TITLE
可以把宿舍里满心请的人腾出来么

### ISSUE THREAD

**Issue by fuyn101** [ArkMowers/arknights-mower#456]
既然能稳定给  单回+群回了  可以把宿舍里满心请的人腾出来么

![图片](https://github.com/ArkMowers/arknights-mower/assets/151902446/ea2d4629-e943-4650-96d3-46cbb3abbc9a)

恢复心情的时间，至少有如下干扰
流明和电站的数量（城西格雷伊，L2）
冰酿的0.8平分给心情不满的人
纯烬艾雅法拉和其他三个行医
等

**Comment by Shawnsdaddy** [comment]
其他任务执行的时候如果有回满心情干员，是会视作空位的。
但是这个比较依靠其他任务的时间，

**Comment by ZhaoZuohong** [comment]
mower暂时不能从这个页面读干员心情

**Comment by Shawnsdaddy** [comment]
可以，加！

原先不太想加的原因是选人太慢了。。现在选人速度大幅提升，想加什么操作都行！

加~加~加~！~
