### ISSUE TITLE
进入房间出错会导致 进入房间出错

### ISSUE THREAD

**Issue by Shawnsdaddy** [ArkMowers/arknights-mower#461]
![image](https://github.com/ArkMowers/arknights-mower/assets/33809511/4121785f-c8a9-4233-8038-ce89d0084eac)

time : 2023-12-28 05:41:44,821

[进错房间.log](https://github.com/ArkMowers/arknights-mower/files/13787748/default.log)

**Comment by ZhaoZuohong** [comment]
用左上角的门牌号校验？

**Comment by Shawnsdaddy** [comment]
> 用左上角的门牌号校验？

不知道，得研究一下 @Konano 是怎么实现的
