### ISSUE TITLE
开party后不会马上自动填入线索

### ISSUE THREAD

**Issue by Hliyy** [ArkMowers/arknights-mower#473]
![QQ图片20240108185924](https://github.com/ArkMowers/arknights-mower/assets/151808537/94dd2437-4401-408b-86d3-09a5ea8d30fc)
开party后似乎不会马上自动填入线索，可能会降低好友给予相应线索的概率

**Comment by Shawnsdaddy** [comment]
这个线索的话，你不填，好友也是知道你有的。。
好友视角
![image](https://github.com/ArkMowers/arknights-mower/assets/33809511/5c75b88e-fc16-4e67-ab68-64356c84fee8)

一个没填
![image](https://github.com/ArkMowers/arknights-mower/assets/33809511/8c8e390e-8ada-4043-9735-3188d517c87d)
