### ISSUE TITLE
稀音在心情耗尽时仍有可能会红脸工作

### ISSUE THREAD

**Issue by Anyk00** [ArkMowers/arknights-mower#476]
从心情报表里可以看出来每次在心情耗尽时都会红脸工作一段时间，经过观察是因为在稀音休息时烟火组下班把宿舍位置占满，导致稀音组回去上班，在等待烟火组休息完毕的过程中会使稀音红脸工作。
![image](https://github.com/ArkMowers/arknights-mower/assets/132000824/961f2fde-2f80-430b-b576-bb53f493e3fe)

**Comment by ZhaoZuohong** [comment]
发日志

**Comment by Shawnsdaddy** [comment]
@Anyk00 下次碰到提供下Log, 我今天也遇到了，但是不确定是否和你的情况一样，先修一下我遇到的情况.

是遇到稀音需要挤出正在休息的相同替换组。然后任务删除有误导致没有计算稀音的时间

**Comment by Shawnsdaddy** [comment]
哎呀，好像不是一个问题

**Comment by Anyk00** [comment]
![image](https://github.com/ArkMowers/arknights-mower/assets/132000824/cd15b39a-b3f9-408e-97c4-f9978bd515fc)
[runtime.log](https://github.com/ArkMowers/arknights-mower/files/14134752/runtime.log)
又出现了稀音红脸的情况，log已附上

**Comment by Shawnsdaddy** [comment]
目前暂时没有心情消耗变化刷新倒计时的功能
