### ISSUE TITLE
卡在基建干员筛选页面无限循环

### ISSUE THREAD

**Issue by RichardOUC** [ArkMowers/arknights-mower#478]
模拟器版本：mumu12 V3.5.17(2076)
mower版本：v3.5.0-alpha-21+7ec4bed
问题：
经常（~2周一次）卡在按类别筛选干员页面（图1。非BUG实时截图，是后补的截图，可能不能完全复现bug时游戏截图），同时mower卡死+循环（图2）。日志见附件
[log.zip](https://github.com/ArkMowers/arknights-mower/files/14003856/log.zip)

![fig1](https://github.com/ArkMowers/arknights-mower/assets/90265841/c08721fc-b5f3-42a4-b868-075741a23c82)
![fig2](https://github.com/ArkMowers/arknights-mower/assets/90265841/947b9ab8-d843-4503-8120-5082b678eff9)

**Comment by ZhaoZuohong** [comment]
commit b5a79aa6283d908926e31ef2326b5a4887b5aaf7 更换了 `arrange_blue_yes.png`，在 400 张截图下测试正常

**Comment by RichardOUC** [comment]
谢谢EE！
