### ISSUE TITLE
若干个互不影响的副表条件同时满足时来回触发

### ISSUE THREAD

**Issue by BaiYu-yosa** [ArkMowers/arknights-mower#479]
开发者您好：    
       这是一个建议。
       我目前是有两个条件，戴菲恩上班时两贸易站内干员换位和impart关闭时上陈，这两个条件是互不影响的，如果我单独写这两个条件，当这两个条件都满足时每次结束任务就会检测条件导致副表一和副表二来回切，我只能枚举所有情况写三个副表。但现在我有了涤火杰西卡上班时2-1梅尔换杏仁的需求，和贸易战换位、impart条件也互不相关，那我就得枚举写5个副表了，太繁复了也容易导致条件粗心写错。
       所以能否让若干个互不影响的副表条件满足时，将对应的任务合并一起触发。这样也有个好处就是搬别人的副班条件时更好搬，不用枚举重写太多副表和重复的条件了，能让一个副表像一个模块一样方便整理思路，简化了像impart这样的常驻大前提条件的编写。
       来回切换的问题是一开始用副表的时候遇到的了，当时用枚举笨办法解决了就没留截图，故附上现在的枚举排班表作为参考。
       希望能被采纳，谢谢！
![21贸2书3赤金](https://github.com/ArkMowers/arknights-mower/assets/101352523/4eefbe7e-9f03-4b46-b4f9-2775b82e5050)

**Comment by sinoYukisama** [comment]
图附错了，不好意思，是这个两书三赤金
![Uploading 21贸2书3赤金.png…]()
的表

**Comment by Shawnsdaddy** [comment]
我来看看是谁在点赞.jpg

**Comment by sinoYukisama** [comment]
乐

**Comment by Shawnsdaddy** [comment]
新增附表逻辑可以多个附表同时触发
