### ISSUE TITLE
正常识别scene但点击位置错误

### ISSUE THREAD

**Issue by HoverSoul** [ArkMowers/arknights-mower#484]
偶尔会碰到这种识别首页正确但无法点击基建按钮的情况，会一直卡在这个界面几个小时都不动。（估计是点击基建失败，识别到首页，点基建失败，循环）建议添加超过多少次同一个scene时，重启游戏

新年活动前就有这个bug，不是因为鹰角更新才导致的

![image](https://github.com/ArkMowers/arknights-mower/assets/26949076/2e5c6809-0317-476f-97b1-e2ec30ca47d5)

**Comment by HoverSoul** [comment]
新年活动前就有这个bug，不是因为鹰角更新才导致的

**Comment by ZhaoZuohong** [comment]
发日志

**Comment by ZhaoZuohong** [comment]
没有日志没法修
