### ISSUE TITLE
稀音安排休息时未成功吃到单回

### ISSUE THREAD

**Issue by Oybo2000** [ArkMowers/arknights-mower#490]
日志如下[runtime (1).log](https://github.com/ArkMowers/arknights-mower/files/14266923/runtime.1.log)

稀音于21：38：17被安排进入1号宿舍，但是没有触发非低优先干员进驻已经存在低优先干员的宿舍是进行顺序重排的操作，导致稀音没有吃到单回，回满倒计时达到10h。

**Comment by ZhaoZuohong** [comment]
![image](https://github.com/ArkMowers/arknights-mower/assets/34163622/bdd62dd5-f090-4a09-ab73-9d3c3c80a679)

宿管只有波登可，稀音未吃到单回

**Comment by ZhaoZuohong** [comment]
2 号位置是单回位，3、4、5是群回位。

在排班前，宿舍的单回位干员不在排班表中。断罪者、陈都在排班表中，且设置了低优先级，2 号位不在排班表中的干员吃单回。换成稀音后，断罪者和陈未重新安排，撤下单回位干员、安排稀音时，单回落在陈上了。

[runtime.log](https://github.com/ArkMowers/arknights-mower/files/14392876/runtime.log)

**Comment by ZhaoZuohong** [comment]
卡夫卡休息的时候没有吃到单回

[runtime.log](https://github.com/ArkMowers/arknights-mower/files/14409271/runtime.log)

**Comment by Shawnsdaddy** [comment]
> 回位干员不在排班表中。

我默认free会自动重新安排没想到free在某些特定情况下不会变的情况

**Comment by Shawnsdaddy** [comment]
稍微思考了一下，不太好修

**Comment by ZhaoZuohong** [comment]
换一种实现方式吧，让单回落到单回位置上，一切就变得特别简单了
不论宿舍安排什么干员，总是分两步进驻，第一步放宿管和单回位干员，第二步再放群回位干员
简单无脑，还能知道单回位的有没有吃到单回

**Comment by Shawnsdaddy** [comment]
> 换一种实现方式吧，让单回落到单回位置上，一切就变得特别简单了 不论宿舍安排什么干员，总是分两步进驻，第一步放宿管和单回位干员，第二步再放群回位干员 简单无脑，还能知道单回位的有没有吃到单回

不是，得小改一下安排干员+验证逻辑。。因为有把干员X出去的情况

**Comment by Shawnsdaddy** [comment]
我试了一下第一次只安排单回干员，验证会挂，而且如果宿舍已经是满了，会出错

我在想是否新增一个新词条,empty或者用什么其他的方法容易实现

**Comment by ZhaoZuohong** [comment]
![image](https://github.com/ArkMowers/arknights-mower/assets/34163622/260bda53-9fc4-4877-83d0-799b40addd88)

**Comment by Shawnsdaddy** [comment]
@Oybo2000 新版本加了排序，没问题就请close:)
