### ISSUE TITLE
开始执行后纠错建议

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#492]
![image](https://github.com/ArkMowers/arknights-mower/assets/137869765/c6933b1f-7dca-4598-8e71-91048901ed98)
这个完全可以把一个低优先的干员放进高优先位置休息，而不是修错要求增加低优先的位置（如果通过将某个低优先的干员修改为高优先，则会导致低优先干员回满心情后频繁上下班）

**Comment by czt635** [comment]
人间烟火的挂件 加缪缪挂件，又有干员在专精，已经空不出宿舍位了

**Comment by ZhaoZuohong** [comment]
> 把一个低优先的干员放进高优先位置休息

那你为什么在排班表里设置低优先级呢？
