### ISSUE TITLE
找推王优化

### ISSUE THREAD

**Issue by Luoxcat** [ArkMowers/arknights-mower#495]
是否可以先快速拉到最后， 再往回找，这样快一点？

**Comment by ZhaoZuohong** [comment]
目前的 droidcast 分支，换上推王摩根，要 78 秒

**Comment by ZhaoZuohong** [comment]
https://github.com/ArkMowers/arknights-mower/commit/33235f8d9aaa53af6a01f77cc41c4d65daf1e1e2

改进了 detail_filter 实现，可以检测和开关“后勤类技能”筛选选项了

**Comment by ZhaoZuohong** [comment]
https://github.com/ArkMowers/arknights-mower/assets/34163622/87488fe7-0736-4e76-ab61-51aa6e84669f

10 秒找到
