### ISSUE TITLE
mower陷入循环，不停生成任务，但是不执行

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#496]
![image](https://github.com/ArkMowers/arknights-mower/assets/137869765/7ab25e50-609e-4e78-ae2b-1c5bdc9406f8)
[runtime.log](https://github.com/ArkMowers/arknights-mower/files/14395221/runtime.log)

**Comment by Shawnsdaddy** [comment]
新版本还有问题嘛，没有请close 谢谢
