### ISSUE TITLE
账号里没有年, 却检测到干员年

### ISSUE THREAD

**Issue by Luoxcat** [ArkMowers/arknights-mower#502]
![image](https://github.com/ArkMowers/arknights-mower/assets/5655054/4e63a401-9d3c-4a34-b8a6-24f7fbaef3d2)
![image](https://github.com/ArkMowers/arknights-mower/assets/5655054/3ee005f2-d4bd-485e-b038-9addc16582a8)

**Comment by Luoxcat** [comment]
[runtime.log](https://github.com/ArkMowers/arknights-mower/files/14459585/runtime.log)

**Comment by ZhaoZuohong** [comment]
![image](https://github.com/ArkMowers/arknights-mower/assets/34163622/1abe2b2b-0148-4af7-8d63-2ce113dda8d2)

![sc](https://github.com/ArkMowers/arknights-mower/assets/34163622/e4e35d65-c3bc-422d-9fad-ba9be83eb458)

使用这张截图无法复现

**Comment by Luoxcat** [comment]
> ![image](https://private-user-images.githubusercontent.com/34163622/309439972-1abe2b2b-0148-4af7-8d63-2ce113dda8d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNTc3OTYsIm5iZiI6MTcwOTM1NzQ5NiwicGF0aCI6Ii8zNDE2MzYyMi8zMDk0Mzk5NzItMWFiZTJiMmItMDE0OC00YWY3LThkNjMtMmNlMTEzZGRhOGQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDA1MzEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NGMyZDZlMzQ3ODdmZTY0MzkxYjEyYzk2YzY5NzE2MTU3MTFiZjcyYWY2OWIyM2M2NWI3ZTQ2MTAwMGRkNjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.blMi2-iqEMYOsfniZSb_TGIeYyMkGOxEsMMQCmIR-5Y)
> 
> ![sc](https://private-user-images.githubusercontent.com/34163622/309439985-e4e35d65-c3bc-422d-9fad-ba9be83eb458.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzNTc3OTYsIm5iZiI6MTcwOTM1NzQ5NiwicGF0aCI6Ii8zNDE2MzYyMi8zMDk0Mzk5ODUtZTRlMzVkNjUtYzNiYy00MjJkLTlmYWQtYmE5YmU4M2ViNDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAyVDA1MzEzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlNzgzMDkwOTNiZjI5Mjg4NjMwZWUzMjYxMzY3MDg2NmZiYzY0NzFjYTVjYWE5YTdjZjdlMmRiOGIzMTNiYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mOwoPiXwShpPIz1zbssYzgBPo-OBRC-mbzNTlnNVwzQ)
> 
> 使用这张截图无法复现

奇怪, 后面用调香师替换了
