### ISSUE TITLE
卡首页循环刷屏，无法继续执行任务

### ISSUE THREAD

**Issue by 383175186** [ArkMowers/arknights-mower#507]
23.05的日志，开始循环首页刷屏，手动暂停启动就正常了

![52ea6d7221d2b609fa33f161df568b81](https://github.com/ArkMowers/arknights-mower/assets/29884371/0559d8ec-3ff6-4119-9c89-55d027e170fe)
![20240305230806](https://github.com/ArkMowers/arknights-mower/assets/29884371/6ed28dd8-abe1-4bcf-8202-5521d3ee5530)
[runtime - 副本.log](https://github.com/ArkMowers/arknights-mower/files/14497388/runtime.-.log)

**Comment by ZhaoZuohong** [comment]
日志中点击的坐标没问题，推断是scrcpy的问题

**Comment by Shawnsdaddy** [comment]
这个好像原来也出现过，无法复现

**Comment by ZhaoZuohong** [comment]
我计划把scrcpy升级一下

**Comment by ZhaoZuohong** [comment]
试试 01e55e845d3c6680d5d82fd747cff4e26de9f3c8 的 MaaTouch
