### ISSUE TITLE
未进驻筛选点错成产出设施

### ISSUE THREAD

**Issue by Jimmychen0258** [ArkMowers/arknights-mower#511]
[出错时间20240307 022235.zip](https://github.com/ArkMowers/arknights-mower/files/14517455/20240307.022235.zip)

**Comment by Jimmychen0258** [comment]
版本 296817b，3.1号在群里提过

**Comment by Jimmychen0258** [comment]
---原始邮件---
发件人: "Zhao ***@***.***&gt;
发送时间: 2024年3月7日(周四) 中午12:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ArkMowers/arknights-mower] 未进驻筛选点错成产出设施 (Issue #511)




  
3.1号在群里提过
  
贴一下聊天记录

**Comment by Jimmychen0258** [comment]
![Uploading Screenshot_20240307_123701_com.tencent.mobileqq.jpg…]()

**Comment by Jimmychen0258** [comment]
![Screenshot_20240307_123701_com tencent mobileqq](https://github.com/ArkMowers/arknights-mower/assets/131239637/78283c73-d564-43d4-99b6-63bfc48d06b8)

**Comment by ZhaoZuohong** [comment]
之前没有保存截图， 7dc3eb79d607ab03e1ea68d259c5a1691f6beef6 加了截图，下次遇到时看看截图什么样
