### ISSUE TITLE
优化建议：在排班表干员头像上，添加优先级标识

### ISSUE THREAD

**Issue by 383175186** [ArkMowers/arknights-mower#513]
![image](https://github.com/ArkMowers/arknights-mower/assets/29884371/80a91cfb-50fc-497a-9c8f-2d96d2f0a80f)
类似这种效果，角标三角红绿配色来区分高低优先级。
作用主要是用来查看作业时，快速区分同组高优数量，以及是否设置正确。
现阶段的版本中，需要对着低优表格和排班表一对一检查，不仅费时，而且难免看漏。
与之相对的在分享图片作业时，也能快速浏览看到具体优先级安排。

**Comment by Shawnsdaddy** [comment]
暂时没有这个计划，因为以后要自动优先级

**Comment by ZhaoZuohong** [comment]
现在低优先级有重排了，设置的含义是“一组里有多少个干员去低优先级位置休息”，不是让特定干员去低优先级；

> 自动优先级

这个做不到，有些低优先级的信息只能手动指定
