### ISSUE TITLE
初始化mower时报错并循环关闭开启模拟器

### ISSUE THREAD

**Issue by HoverSoul** [ArkMowers/arknights-mower#518]
版本4026351
初始化mower时报错并循环关闭开启模拟器
ValueError: cannot reshape array of size 8294396 into shape (1080,1920,4)
[runtime.log](https://github.com/ArkMowers/arknights-mower/files/14597412/runtime.log)
[252_2赤金搓玉030124.json](https://github.com/ArkMowers/arknights-mower/files/14597422/252_2.030124.json)

**Comment by ZhaoZuohong** [comment]
52bd3a0ba91a8cb9ccf9d5ce6c2c3e51f11ae30b 修了
