### ISSUE TITLE
设置异格格雷伊回满，出现不生效的情况

### ISSUE THREAD

**Issue by 383175186** [ArkMowers/arknights-mower#519]
![image](https://github.com/ArkMowers/arknights-mower/assets/29884371/5bbb7377-0f82-49bc-9bdc-2d15c9fb7efc)
![image](https://github.com/ArkMowers/arknights-mower/assets/29884371/8614b6d8-69b3-4997-833c-8e6953fae4c7)
手边有四五个号出现这个情况，额外增加温蒂回满时，休息时间就又正常了

**Comment by Shawnsdaddy** [comment]
当前是最低是森蚺，所以就不生效了
