### ISSUE TITLE
能否新增暂停功能

### ISSUE THREAD

**Issue by DreAmVirGo** [ArkMowers/arknights-mower#532]
有时候想暂停mower（在关卡内不方便退出），但是mower只有停止后重新开始的选项。
能不能新增一个暂停的功能，继续的时候读取当前任务表
主要是每次重开mower都会重新调用maa，读取仓库等等一系列事情，如果只是记住多久之前调用的maa，对照当前时间不重新折腾一大通也可以。。。

**Comment by Shawnsdaddy** [comment]
可以加个启动选项，读取预存数据启动（适合暂停）或者重新大重启（适合出错的时候使用）

@ZhaoZuohong

**Comment by Shawnsdaddy** [comment]
@DreAmVirGo 加了，群文件下载9.2版本
