### ISSUE TITLE
清理智的功能，前期稳定，运行一段时间后会失效

### ISSUE THREAD

**Issue by ghzh21th** [ArkMowers/arknights-mower#534]
[runtime.log](https://github.com/ArkMowers/arknights-mower/files/14812700/runtime.log)
[asst - 副本.log](https://github.com/ArkMowers/arknights-mower/files/14812701/asst.-.log)
清理智的功能，前期稳定，运行一段时间后会失效。
两个日志已附上。mo日志中显示调用了maa，但没有清理智，此时点击测试设置不会返回结果。
![QQ图片20240331005256](https://github.com/ArkMowers/arknights-mower/assets/136472006/557ffba2-1d89-4bb1-aeda-58d074451028)

**Comment by Shawnsdaddy** [comment]
新版本无，以后有问题再reopen
