### ISSUE TITLE
希望可以增加加一个在宿舍人员发生变动后及时更新其他人员回满时间以及清除多余宿舍闲人释放任务的功能

### ISSUE THREAD

**Issue by Oybo2000** [ArkMowers/arknights-mower#537]
目前我遇到的有
1 不养闲人功能生成的 闲人 下班的任务，在排班表主力干员进驻宿舍将 闲人 挤出宿舍后没有及时清除的情况
2 宿舍低优先干员在其他干员回满后吃到单回，不会更新该干员的回满时间（不是bug），希望后续可以在宿舍人员发生变动后，自动更新所有宿舍人员的回满时间。一方面可以检测单回是否正常落到VIP干员上，另一方面可以及时将单回变动后回满时间缩短的干员及时拉去上班。以下以伊内丝为例举一个单回转移后低优先干员回满变动的实际例子。
![U
![S40404-14590878_com hypergryph arknights](https://github.com/ArkMowers/arknights-mower/assets/140508232/a39891a1-cbb0-43c6-858a-79d47b4e4779)
ploading S40404-14593051_com.tencent.androidqqmail.png…]()

**Comment by Shawnsdaddy** [comment]
这个逻辑已经加了
