### ISSUE TITLE
宿舍里出现需要回满心情的干员被安排出来工作

### ISSUE THREAD

**Issue by kyleonli** [ArkMowers/arknights-mower#548]
大佬们好，事情是这样的
我17号上午更新5c0c0c5版本后，在雷电9模拟器上面运行mower，16点左右看到出现了2个相同的排班任务

![V(4IQ6WY`F3OYJQBFIH6@5V](https://github.com/ArkMowers/arknights-mower/assets/97153705/a5dde67b-f517-44b9-9722-d64ae503e14e)

我看到后检查了一下心情报表看他们是否安装设定回满心情后再上班
（这是我的排班，伊内丝w赫德雷一家人整整齐齐的设置到了一组，伊内丝赫德雷需要回满，伊内丝需要耗尽，没有副表）

![252-33-感知红松](https://github.com/ArkMowers/arknights-mower/assets/97153705/3b3e2a92-e63a-4f66-8961-bad61dc777c2)

但是我看到心情报表显示他们并没有回满就回去工作了

![10JJK2PJ){4X7`KW@9AA 0N](https://github.com/ArkMowers/arknights-mower/assets/97153705/9dc2fd9e-9dd3-406d-ada0-5ad7ae07c751)

我先在群里问了一下群友们是不是我设置有问题，e佬建议我问问大哥或者发个issue
各位群友建议我1，将w结伴并设置0心情工作，2，将赫德雷设置低优先级
我先按照群友说的改一下，如果大佬们看到了可以指正一下我设置的不对的地方吗？
这个是我的log和设置，

[runtime.txt](https://github.com/ArkMowers/arknights-mower/files/15009091/runtime.txt)

![B~ 00_H0GIYXL}6GR4U~ZM](https://github.com/ArkMowers/arknights-mower/assets/97153705/3803f476-6cb4-40f7-84cf-f9c465944739)

**Comment by kyleonli** [comment]
不好意思，截图是17点的，16点的截图在这里

还有一个是他们被换班出来的记录

**Comment by Shawnsdaddy** [comment]
log 没有涵盖具体任务是怎么生成的时间段

**Comment by Shawnsdaddy** [comment]
新版本没问题就关了，有问题再提
