### ISSUE TITLE
get_agent_from_room 如果出错会无限循环卡死

### ISSUE THREAD

**Issue by Shawnsdaddy** [ArkMowers/arknights-mower#549]
需要加个退出机制

https://github.com/ArkMowers/arknights-mower/blob/dev_shawn/arknights_mower/solvers/base_schedule.py#L2122

![image](https://github.com/ArkMowers/arknights-mower/assets/33809511/233f8595-108d-47cf-bea1-f722ee9d09f7)

**Comment by ZhaoZuohong** [comment]
出错了再说

**Comment by ZhaoZuohong** [comment]
而且需要加的不是退出机制，是检测当前场景是否正确。如果正确地在站里，除非游戏有问题，不然不可能卡死。
