### ISSUE TITLE
调整贸易站干员后，移除5分钟内的跑单任务失败

### ISSUE THREAD

**Issue by 1353587086** [ArkMowers/arknights-mower#550]
![image](https://github.com/ArkMowers/arknights-mower/assets/24757168/b8cf871b-a43a-454c-8cd9-218f1ce0c698)
[8.21分调整了贸易站的干员，将鸿雪组替换为孑银灰，日志提示移除超过5分钟的跑单任务以刷新时间、实际8.23分显示下一条任务列表中，跑单任务未被移除。导致最终跑单任务时间与实际时间偏差较大，引发漏单。
[runtime.log](https://github.com/ArkMowers/arknights-mower/files/15032589/runtime.log)

**Comment by 1353587086** [comment]
通知调整了贸易站101和301，但是只移除了贸易站301的跑单任务，贸易站101的，没有移除

**Comment by Shawnsdaddy** [comment]
超过15分钟才会被移除。15分钟以内默认效率影响不大。
你是不是阈值时间设置太低了建议4-5分钟左右

**Comment by 1353587086** [comment]
> 超过15分钟才会被移除。15分钟以内默认效率影响不大。 你是不是阈值时间设置太低了建议4-5分钟左右

是指“跑单前置延时”吗，我是设置的5分钟。这里鸿雪换银灰，时间从12分钟变成了16分钟多，订单时长变长了4分多钟，几乎把阈值时间的4~5分钟吃完了，再加上切换站点需要的时间，我需要把阈值时间拉倒9分钟比较保险

**Comment by Shawnsdaddy** [comment]
我觉得可以单独出个任务叫刷新跑单时间。。这样的话可能规避掉这种问题

**Comment by 1353587086** [comment]
最近意识到阈值时间拉长并不能完全解决这个问题。高效率上班低效率下班，可以被跑单前置延时覆盖。但是低效率上班高效率下班，导致跑单完成时间覆盖了另外一个贸易站的跑单任务，是需要拉长跑单任务间隔来避免影响的，目前这个跑单任务间隔也是固定5分钟，并不受跑单前置延时的影响
