### ISSUE TITLE
肥鸭充能新模式：心情混合恢复方案

### ISSUE THREAD

**Issue by ZhaoZuohong** [ArkMowers/arknights-mower#551]
## 肥鸭系数：是赚还是亏，一算就知道

我们希望在消耗同样多的肥鸭心情时，获得更多的产出。举例而言，自动化组的清流和温蒂安排在2级制造站，若不使用肥鸭充能，替换组可安排双人 62% 的泡泡火神。若使用肥鸭为清流充能，温蒂休息时，清流只能搭配 30% 效率的干员。肥鸭充能清流，清流消耗肥鸭充给她的心情。与不充能相比，这段时间内，制造站效率由 62% 提升为了 70%，效率差为 8%. 清流额外工作时间为

$$
\text{清流的额外工作时间} = \frac{\text{肥鸭充能心情}}{\text{清流的心情消耗速率}}
$$

最终，肥鸭充清流的心情带来的产出提升为肥鸭充能的心情乘以效率差，再除以心情消耗速率。

$$
\text{肥鸭心情带来的产出提升} = \text{肥鸭充能的心情} \times \frac{\text{效率差}}{\text{心情消耗速率}}
$$

我们希望肥鸭发挥更大的作用，也就是在消耗同样的肥鸭心情时，获得更高的产出提升。因此定义肥鸭系数为

$$
\text{肥鸭系数} = \frac{\text{产出提升}}{\text{充能心情}} = \frac{\text{效率差}}{\text{心情消耗速率}}
$$

对于上述自动化的例子，肥鸭系数为 $0.08 \div 0.7 \approx 0.114$。

再来看黑钢组的例子。中枢涤火杰西卡的心情消耗速率为 1.25。组内还有其他干员：水月、香草、杰西卡的效率为 100%，心情消耗速率为 0.65；杏仁的效率为 36%，心情消耗速率为 0.45。黑钢组休息时，水月三人使用泡泡、火神、贝娜作为替补，效率为 93%；杏仁使有梅尔作为替补，效率为 30%. 主力与替补的效率差为 $1 + 0.36 - 0.93 - 0.3 = 0.13$。涤火杰西卡是组里的心情瓶颈，我们可以适当地用肥鸭为其充能，增加整组的工作时间占比。涤火杰西卡的肥鸭系数为 $0.13 \div 1.25 \approx 0.104$。

**注意**：比较不同种类的效率时，可能需要额外的换算。

## 充能算法：三条简单规则，暖机分组随意充

假如我们选出了数名干员用于接受肥鸭充能，**心情消耗速率之和大于 2，并按肥鸭系数降序排列**。当肥鸭心情回满时，准备接受充能的干员不论在工作还是在宿舍休息，都可以接受充能，随后立即进入工作站工作。那么，我们应当如何选择接受充能的干员呢？只要遵循三条规则即可。

**规则一**：不选择心情太高的干员。如果我们一直选择心情特别高的干员充能，肥鸭在充能后会很快回满心情继续充能，导致任务特别频繁。所以，增添“肥鸭阈值”的设置，使肥鸭仅充能心情低于肥鸭阈值的干员。推荐值为 90%，充能间隔至少为 1.2 小时，不会过于频繁。

以往的肥鸭充能使用 N+1 模式，要求充能列表的前 N 名干员心情消耗速率之和低于 2、N+1 名干员的心情消耗速率之和高于 2。然而在某些情况下，有些干员带有心情减免效果，使得心情消耗速率的计算比较复杂。使用新的充能算法时，只需要按肥鸭系数降序排列写好足够多的干员，充能时便会优先满足肥鸭系数更高的干员，如果有多余的心情，再分给肥鸭系数较低的干员。N+1 模式的前 N 名干员不会进入宿舍休息，然而，新算法的肥鸭阈值如果太低，顺序靠前的干员也会进入宿舍休息。如果想避免靠前的干员进入宿舍休息，可以为其设置 0 心情工作以模拟 N+1 模式。不过最好还是提高肥鸭阈值，这样前 N 名干员心情整体较高时，充能第 N+1 名干员，降低任务频率；前 N 名干员心情较低时，进入宿舍休息，避免红脸。

**规则二**：暖机干员仅在宿舍内充能。暖机干员在站内工作时，充能会打断暖机效果，降低效率，很不划算；肥鸭的心情回满时间也很难与暖机干员心情用尽的时间恰好对齐。因此，让暖机干员先进入宿舍休息一小段时间，肥鸭回满后再对其充能。对于暖机干员，仍然建议提高肥鸭阈值，缩短肥鸭充能的周期，使暖机干员进入宿舍后尽早接受充能。

**规则三**：有分组的干员，心情为组内最低时充能。以黑钢为例，涤火杰西卡的心情消耗速率远高于组内的其他干员。如果少量地为涤杰充能，可以延长黑钢组的工作时间占比。然而，如果肥鸭为涤杰充能的心情过多，组内其他干员的心情跟不上涤杰，肥鸭的心情就会被浪费。那么，怎样确定合理的充能频率与充能心情呢？我们可以观察黑钢组的心情。如果不充能涤杰，涤杰的心情总是低于组内其他干员。充能后，涤杰的心情变为组内最高，但几轮工作和休息后，其领先的心情被逐渐追平和反超，这时就是适宜的充能时机。因此，接受充能的干员如果有分组，应该在其心情为组内最低时进行充能。

对于有分组的干员，还是建议提高肥鸭阈值，减小每一次充能的心情，避免与组内其他干员拉开过大的心情差。同时还要注意，刚完成充能的干员，心情在一段时间内会保持组内最高。整组休息时，如果组内有设置低优先级，就会将这名干员安排到群回位置休息，对于整组的工作时间占比不利。因此，**进行低优先级自动重排时，如果有干员在肥鸭充能的列表中，需避免将其设置为低优先级。**

有时，我们希望利用肥鸭延长整组的工作时间占比，例如 22 贸下充能绮良、鸿雪、图耶。然而，这三名干员的心情消耗速率之和大于 2，使用以往 N+1 的模式无法实现这一想法。使用新的充能算法时，只需要将三名干员保持分组并写入肥鸭列表。肥鸭每轮会选择组内心情最低的干员进行充能，整组心情较低时依然一起进入宿舍休息。此时依然建议使用较高的肥鸭阈值，使组内心情差距不要太大。

用户将适合充能的干员按肥鸭系数降序填入肥鸭的替换组中，保证所有干员的心情消耗速率大于 2。当肥鸭心情回满时，mower 遍历肥鸭列表，依次检查，为列表中符合三条规则的最靠前的干员充能。

最后附上三个例子，进一步说明新算法如何使用。

1. 阿罗玛+槐琥：两名干员不分组，均填入肥鸭列表的靠前位置，并为槐琥设置 0 心情工作。阿罗玛工作时，肥鸭为槐琥及其他干员充能。当阿罗玛进入宿舍休息后，肥鸭为阿罗玛充能，阿罗玛立即上班，需要槐琥为其消除心情消耗影响，但肥鸭需要很长时间才能回满心情。设置 0 心情工作，阻止槐琥进入宿舍休息，等到肥鸭心情回满后就可为槐琥充能了。
2. 清流+温蒂：两名干员不分组，为清流设置 0 心情工作，以避免温蒂工作但清流休息时清流的替换被温蒂清除效率。
3. 稀音+红云+帕拉斯：三名干员分组，为红云和帕拉斯设置宿舍低优先级。如果稀音一进入宿舍就立即对其充能，红云和帕拉斯的心情不足以支撑到稀音第二次休息。在没有心情消耗减免时，红云与帕拉斯至少有 $24 \div 0.65 \times 0.4 \approx 14.77$ 心情，才可以为稀音充能。因此设置副表，条件为红云与帕拉斯的心情大于 14.77，在此副表中将稀音填入肥鸭充能列表。

**Comment by Shawnsdaddy** [comment]
挺好，加个开关就行
