### ISSUE TITLE
宿舍安排干员休息时发生卡死

### ISSUE THREAD

**Issue by Anyk00** [ArkMowers/arknights-mower#552]
在安排宿舍free干员时mower日志显示关闭所有筛选后点击（1824，54），实际上尚未进入安排宿舍干员界面，（1824，54）位置为清空宿舍，之后卡死在宿舍界面。
版本是fab03ba，卡死日志从15：00：58开始，由于没有触发自动截图，因此手动截了卡死状态的图（非出问题时刻截图）
[runtime - 副本.log](https://github.com/ArkMowers/arknights-mower/files/15038233/runtime.-.log)
![卡死界面](https://github.com/ArkMowers/arknights-mower/assets/132000824/fb41a554-6310-48f6-b38a-07b6e0c1333c)

**Comment by ZhaoZuohong** [comment]
出问题的是哪个版本？

**Comment by Anyk00** [comment]
![version](https://github.com/ArkMowers/arknights-mower/assets/132000824/1cf341d7-5e39-417b-8573-f08a7527daa0)
16号更新的这个版本
