### ISSUE TITLE
换班时出现循环报错

### ISSUE THREAD

**Issue by 1353587086** [ArkMowers/arknights-mower#565]
版本号b74c1f8
[upload-runtime.log](https://github.com/ArkMowers/arknights-mower/files/15130173/upload-runtime.log)
14点13分跑单任务，预估14点22分完成跑单，临时生成了凯尔希阿米娅巫恋的下班任务，然后出现报错循环，产生了大量日志及一个超长的换班任务，再早的日志被覆盖了找不到，只能找到14:30的日志
![Y2WEVAKM` 03}C CUIZTT05](https://github.com/ArkMowers/arknights-mower/assets/24757168/93536db2-c837-42ce-afd0-0d70664a615c)

**Comment by Shawnsdaddy** [comment]
这个log没啥用。并没有报错时的日志

还有为什么凯尔希/阿米娅要设置用尽？

**Comment by 1353587086** [comment]
> 这个log没啥用。并没有报错时的日志 从14:30开始的 ![image](https://private-user-images.githubusercontent.com/33809511/326219673-7dfb895e-2785-49f8-9b38-f1b01708ffef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNjk0MzIsIm5iZiI6MTcxNDI2OTEzMiwicGF0aCI6Ii8zMzgwOTUxMS8zMjYyMTk2NzMtN2RmYjg5NWUtMjc4NS00OWY4LTliMzgtZjFiMDE3MDhmZmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDAxNTIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlOTZiYWQwOTFhMzRiOWIwYTI4NWViMzQ4NDQ1N2FlYTk5NzljYzJiMTBjZDYyN2Q0ODgzZGIxOGVjODg4MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HE8pFXHv26SsBleWqz9oqzJa8ukKkS15Maydvc2wr-w)
> 
> 还有为什么凯尔希/阿米娅要设置用尽？

这个bug发生时会产生大量日志，基本上四五分钟就把20个日志文件写完了，再早的日志看不到了。那就等哪次再发现这个bug恰巧还有日志时再提issue了？

**Comment by Shawnsdaddy** [comment]
> > 这个log没啥用。并没有报错时的日志 从14:30开始的 ![image](https://private-user-images.githubusercontent.com/33809511/326219673-7dfb895e-2785-49f8-9b38-f1b01708ffef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNjk0MzIsIm5iZiI6MTcxNDI2OTEzMiwicGF0aCI6Ii8zMzgwOTUxMS8zMjYyMTk2NzMtN2RmYjg5NWUtMjc4NS00OWY4LTliMzgtZjFiMDE3MDhmZmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDAxNTIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlOTZiYWQwOTFhMzRiOWIwYTI4NWViMzQ4NDQ1N2FlYTk5NzljYzJiMTBjZDYyN2Q0ODgzZGIxOGVjODg4MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HE8pFXHv26SsBleWqz9oqzJa8ukKkS15Maydvc2wr-w)
> > 还有为什么凯尔希/阿米娅要设置用尽？
> 
> 这个bug发生时会产生大量日志，基本上四五分钟就把20个日志文件写完了，再早的日志看不到了。那就等哪次再发现这个bug恰巧还有日志时再提issue了？ PS:凯尔西阿米亚耗尽是因为替补怪猎一队，猫车绑了巫恋，凯尔西阿米亚心情消耗比巫恋快一点，就让他俩耗尽带巫恋下班了。

为啥要巫恋呢。。没但书？

**Comment by 1353587086** [comment]
> > > 这个log没啥用。并没有报错时的日志 从14:30开始的 ![image](https://private-user-images.githubusercontent.com/33809511/326219673-7dfb895e-2785-49f8-9b38-f1b01708ffef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNjk0MzIsIm5iZiI6MTcxNDI2OTEzMiwicGF0aCI6Ii8zMzgwOTUxMS8zMjYyMTk2NzMtN2RmYjg5NWUtMjc4NS00OWY4LTliMzgtZjFiMDE3MDhmZmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDAxNTIxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlOTZiYWQwOTFhMzRiOWIwYTI4NWViMzQ4NDQ1N2FlYTk5NzljYzJiMTBjZDYyN2Q0ODgzZGIxOGVjODg4MDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HE8pFXHv26SsBleWqz9oqzJa8ukKkS15Maydvc2wr-w)
> > > 还有为什么凯尔希/阿米娅要设置用尽？
> > 
> > 
> > 这个bug发生时会产生大量日志，基本上四五分钟就把20个日志文件写完了，再早的日志看不到了。那就等哪次再发现这个bug恰巧还有日志时再提issue了？ PS:凯尔西阿米亚耗尽是因为替补怪猎一队，猫车绑了巫恋，凯尔西阿米亚心情消耗比巫恋快一点，就让他俩耗尽带巫恋下班了。
> 
> 为啥要巫恋呢。。没但书？

快有了快有了
