### ISSUE TITLE
跑单时间做了其他工作导致漏单

### ISSUE THREAD

**Issue by 861920658** [ArkMowers/arknights-mower#566]
[runtime.log](https://github.com/ArkMowers/arknights-mower/files/15136236/runtime.log)
使用版本为b74c1f8,两次跑单时间为7.57和8.02，在完成7.57跑单后，mower读了心情和无人机加速，导致8.02跑单任务漏单。
![QQ截图20240427092920](https://github.com/ArkMowers/arknights-mower/assets/17093894/67482f02-b4e6-474b-a580-4d17c8098fc0)

**Comment by 861920658** [comment]
感觉两个站挨太近了还是有问题，刚又漏了一单。原因是mower在跑单前执行了一次换班，将两个贸易站的替补班（效率相近）替换成主力班(1站图耶鸿雪能天使，2站绮良黑键巫恋，效率相差大)，此时mower还没有重新读取插拔时间，到了2站插拔的时间执行2站插拔，完成2站插拔后1站就漏单了

**Comment by Shawnsdaddy** [comment]
你这个什么版本的。。请更新一下版本
