### ISSUE TITLE
[版本b74c1f8]卡在赠送线索界面

### ISSUE THREAD

**Issue by 1353587086** [ArkMowers/arknights-mower#567]
![Screenshot_20240427-222440](https://github.com/ArkMowers/arknights-mower/assets/24757168/fff17c90-5da7-4663-9f3e-909f5282a47a)
[runtime - 副本.log](https://github.com/ArkMowers/arknights-mower/files/15138483/runtime.-.log)
21:41:09，在执行赠送线索任务时，卡在截图所示界面，一直提示Scene: 205: 基建放大查看

**Comment by ZhaoZuohong** [comment]
commit f6790d8 或许有帮助
