### ISSUE TITLE
肥鸭充能时干员心情读取错误

### ISSUE THREAD

**Issue by 1353587086** [ArkMowers/arknights-mower#570]
[runtime - 副本.log](https://github.com/ArkMowers/arknights-mower/files/15142836/runtime.-.log)
![Screenshot 2024-04-29 004339](https://github.com/ArkMowers/arknights-mower/assets/24757168/f1c15ebd-c9a9-4048-a913-358b3b740dfb)
22:04肥鸭任务执行时，读到的森蚺心情是12.29，对其进行了充能。此时实际森蚺的心情是14.86（可以在22:05时看到充能后的肥鸭心情是14.86），并不应对其充能。
![image](https://github.com/ArkMowers/arknights-mower/assets/24757168/8a0cd320-4c4e-4af0-8f92-f6802f492e73)

**Comment by ZhaoZuohong** [comment]
Duplicate of #521
