### ISSUE TITLE
生成错误纠错任务导致死循环

### ISSUE THREAD

**Issue by Anyk00** [ArkMowers/arknights-mower#574]
主班表中贸易站B101的干员为[黑键，绮良，鸿雪]，其中黑键属于感知组，绮良鸿雪未绑组，而实际基建中顺序为[绮良，鸿雪，黑键]，因此生成了纠错任务[黑键，current，鸿雪]，在进入贸易站B101后变为安排干员[黑键，鸿雪，鸿雪]，导致无法完成该排班任务，进入死循环。
纠错任务在1：10：27生成，版本为dbdb3a7。
[1：10：27.log](https://github.com/ArkMowers/arknights-mower/files/15152585/1.10.27.log)
<img width="749" alt="排班表主表" src="https://github.com/ArkMowers/arknights-mower/assets/132000824/f767b718-8c67-4404-8bda-f7503f1195f3">
<img width="412" alt="实际顺序" src="https://github.com/ArkMowers/arknights-mower/assets/132000824/ec4a2e8f-a37b-4928-bc50-f68a9af9a7a6">

**Comment by 1353587086** [comment]
当前的纠错任务如果和站内干员相同时，似乎会把已在站内的干员取消选中，然后排序检查发现未选中该干员，然后提示干员选择错误退出选人界面，然后回来重选，重复这个循环造成卡死
