### ISSUE TITLE
识别手动战斗场景，作战中开始任务不强制退出而是等待战斗完成

### ISSUE THREAD

**Issue by lethefrost** [ArkMowers/arknights-mower#575]
当前只能识别prts代理录像的战斗场景，并且等待战斗完成后再开始任务；如果是手动战斗，则会被判定为未知场景并在尝试几次后重启游戏（肉鸽和生稀盐酸忘记看时间被弹出好多好多回了orz悲）

当前似乎是根据检索 `ope_agency_going.png` 等系列图形来判定是否作战中的？可否考虑改为检索左上角的齿轮图标、右下角费用图标、或者右上角二倍速/一倍速/暂停/继续等图标来实现更准确的作战判定？（敌人数量/目标生命似乎在生稀盐酸里不好使）

我目前对mower用的图像匹配和识别技术这块不太熟悉，上面提到的几个视觉元素都有点半透明效果（但是透明度不高），在不同的战斗场景中可能由于背景不同存在微小差异，这种情况会导致匹配失败吗？

**Comment by ZhaoZuohong** [comment]
Why don't you use MowerHelper?

**Comment by ZhaoZuohong** [comment]
我的建议是加强沟通，多了解一下mower现在的状况，然后提出建议，最后再讨论如何实现的细节

**Comment by ZhaoZuohong** [comment]
mower的大部分用户使用QQ群和最近新建的QQ频道

**Comment by ZhaoZuohong** [comment]
Mower的刷生息演算的代码就在仓库里，你看都没看，就来问这部分识别怎么做👀

**Comment by ZhaoZuohong** [comment]
> 不太清楚你具体的意思

我觉得你说的内容不靠谱，mowerhelper为啥不行你也没讲，已经做好的识别还在问该怎么做，那你想让我和你讨论啥

**Comment by ZhaoZuohong** [comment]
> 毕竟也不是想在短短一个提案中解决所有复杂的问题

你先来和一般mower用户接触一下，了解一下现状，再谈解决吧

**Comment by ZhaoZuohong** [comment]
你长篇大论地写，我也要花很多时间去看，而且讲不清楚，非常没意思

**Comment by ZhaoZuohong** [comment]
而且你写的内容里信息依然不足，后续讨论中又牵扯到了其它内容，我们没法专注地讨论这个问题本身

**Comment by ZhaoZuohong** [comment]
到现在为止也没有看到你讨论你的方案的利弊、和mowerhelper的对比，全是在扯没用的，一会儿mowerhelper宣传不到位，一会儿隔壁Issue怎么怎么样

**Comment by ZhaoZuohong** [comment]
你要是觉得Issue里这么扯很高效，那请你继续，我的态度是close as not planned

**Comment by ZhaoZuohong** [comment]
可以预见的是，如果你加了群或频道，很多问题我们几句话就能讲清楚，不管是Bug、更新内容、mower的现状、其他用户的看法、技术上的一些问题，说起来都比较容易；而不是像现在这样，大段大段地发，讨论却完全不在点上

**Comment by ZhaoZuohong** [comment]
> 我只是暂时没有时间深入查看底层实现的细节，不清楚它的具体效果（比方说是否是由于半透明图像匹配不良才导致现在只检查代理，而不是更广泛的作战UI？

> 我并不是在问怎么做，我有看到相关函数和调用的方法

你到底是啥情况，看了还是没看，还是没看懂，我记得生息识别作战中就几行吧

**Comment by ZhaoZuohong** [comment]
> qq 群消息一条一条的刷上去还有其他人讨论其他话题夹在其中

**Comment by ZhaoZuohong** [comment]
> 你到底想要一个事无巨细的对比和分析，还是想要简单的几句话沟通？

该简单的地方简单，该细的地方细，至少应该专注问题本身，而不是一直扯没用的

**Comment by ZhaoZuohong** [comment]
而且mower很早就有开发群，只不过你一直没说过要帮着写，我们就没拉你

**Comment by ZhaoZuohong** [comment]
> 我有点弄不清楚了，你到底想要一个事无巨细的对比和分析，还是想要简单的几句话沟通？

最基本的问题，就问你一句，现在已经有MowerHelper的方案了，不够用吗？为啥这么困难
