### ISSUE TITLE
能否支持一个干员同时绑定两个组,并在计算整组心情回满时不包括该干员

### ISSUE THREAD

**Issue by 861920658** [ArkMowers/arknights-mower#577]
情况:

中枢五人:令.夕,森蚺,焰尾,薇薇安娜,  (令,夕)和(焰尾,薇薇安娜)的替补都设置为怪猎夜刀黑角.贸易站为干员,干员,能天使.
我没有赫德雷,会客室也二级无法用伺夜,最高单人通用贸易效率为35%,我希望在上夜刀黑角时能够自动把能天使换成猫车.但是目前能天使只能随一组上下班.如果随了一组,另一组通过副表实现,这样可能会出现能天使回满心情过快直接拉整组去上班.设置等待xx回满也不是个好办法

目前解决办法;能天使不进行绑组,同时设置多个副表, 但是多个副表直接切换比较缓慢,同时可能会出现夜刀黑角下班了猫车不下班的情况,所以还得再增加一个专门用来纠错的副表,

如果能实现标题功能的话,或许可以减少对副表的依赖,加快mower换班时的效率,提高基建产能,丰富更多的基建玩法,

**Comment by ZhaoZuohong** [comment]
不能

**Comment by Shawnsdaddy** [comment]
没太看懂需求

**Comment by ZhaoZuohong** [comment]
个人建议可以从“该如何实现我排班的XXX需求”开始提问

**Comment by 861920658** [comment]
> 个人建议可以从“该如何实现我排班的XXX需求”开始提问
我已经实现排班需求了: (令,夕)或者(焰尾,薇薇安娜)下班时替换为麒麟夜刀黑角的同时将贸易站的能天使替换为猫车,提高5%贸易效率,通过副表实现.

但是主力下班时需要切换到副表才能让猫车上班,同时主力心情回满后换下夜刀黑角又需要再执行纠错来让猫车下班,我想对这个过程提建议来优化执行时间.

**Comment by ZhaoZuohong** [comment]
起码新开一个Issue，起个正经标题，把排班表放上来
