### ISSUE TITLE
支持UI手动添加任务/专精技能任务

### ISSUE THREAD

**Issue by Shawnsdaddy** [ArkMowers/arknights-mower#593]
- [ ] ~~mata_data 优化，支持同时加多个专精任务~~ （不做了，暂时无法解决安排训练位）
- [ ] #685
- [x] 支持sleep的时候随时添加任务并且启动Mower
- [x] UI实时显示新增任务 Done by @ZhaoZuohong 
- [ ] 支持改，删（只对没运行的任务有效）

**Comment by ZhaoZuohong** [comment]
UI实时显示任务，目前靠的是轮询。以后有机会还是改成服务端通过WebSocket主动推送为好。

**Comment by Snow-dash** [comment]
[bbf7032] 感觉也可以加个强制刷新用尽时间，避免烟火组下班时暖机干员加速消耗红脸。

**Comment by Shawnsdaddy** [comment]
> [[bbf7032](https://github.com/ArkMowers/arknights-mower/commit/bbf70320d69dab93402afe95f9cc151d88a2619e)] 感觉也可以加个强制刷新用尽时间，避免烟火组下班时暖机干员加速消耗红脸。

你来加呗。现在框架都有hhh
