### ISSUE TITLE
第二次任务循坏就会报错

### ISSUE THREAD

**Issue by jy2hao** [ArkMowers/arknights-mower#595]
![Uploading 屏幕截图 2024-05-28 165728.png…]()

**Comment by jy2hao** [comment]
![屏幕截图 2024-05-28 165728](https://github.com/ArkMowers/arknights-mower/assets/119850953/c833ddc6-3780-4e00-bbb2-c87f6513aad2)

**Comment by ZhaoZuohong** [comment]
在 commit 82b5ffa556888302d9bed71e1f91970b094c13d6 中刚修

推荐加入 QQ 频道 ArkMower（频道号：2r118jwue4）
