### ISSUE TITLE
增加手动任务预设

### ISSUE THREAD

**Issue by Snow-dash** [ArkMowers/arknights-mower#604]
即暂时保存任务暂不启动，等需要时再填写时间后一键应用。例如在大更前将但书和巫恋组放入贸易站等非常规操作。（或许可以加个定时停止mower的任务）

**Comment by Shawnsdaddy** [comment]
这个不是有了嘛？雪豹老兄你更新了嘛

**Comment by ZhaoZuohong** [comment]
这个功能，扩展一下，就可以实现定时换班了

**Comment by Shawnsdaddy** [comment]
已经实现了？
