### ISSUE TITLE
森蚺一个多小时了还是没进宿舍休息

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#614]
因为设置了自动化组菲亚充能，但是菲亚充能太频繁，而且休息也很频繁，所以设置了用尽，但是用尽了很久还是没有进宿舍休息（其他自动化干员也会出现这个情况）
或者能否建议 如果全组均为菲亚充能的时候，干员心情阈值能设置得更低一些？
![)2QCHRX$F3 ~%HA4FS 9L6L](https://github.com/ArkMowers/arknights-mower/assets/137869765/e79bdda1-f736-44e1-b4f1-ccb01457e4ad)
[runtime.log](https://github.com/user-attachments/files/15923018/runtime.log)

**Comment by Shawnsdaddy** [comment]
@czt635 

2024-06-21 12:55:46,673 - DEBUG - arknights_mower\solvers\base_schedule.py:310 - overtake_room - 剩余高效:4,低效：3
2024-06-21 12:55:46,674 - DEBUG - arknights_mower\solvers\base_schedule.py:311 - overtake_room - 需求高效:5,低效：1

**Comment by czt635** [comment]
我主表设置的是高效4，附表是设置高效5，附表启用的情况下高效还是4啊？

**Comment by czt635** [comment]
请教一下现在主表和附表下方设置（用尽、低优先之类的）的逻辑是什么样的？附表启用时主附表同时生效？

**Comment by Shawnsdaddy** [comment]
以主表为基础累加

> 请教一下现在主表和附表下方设置（用尽、低优先之类的）的逻辑是什么样的？附表启用时主附表同时生效？
