### ISSUE TITLE
附表条件未满足，但是还是启用了附表

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#618]
设置夕心情小于2启用附表，夕心情为3还是启用了附表
![image](https://github.com/ArkMowers/arknights-mower/assets/137869765/f54a4eb1-75bf-43b8-b468-c7eb10cb2aa3)
[runtime(1).log](https://github.com/user-attachments/files/15942216/runtime.1.log)

**Comment by Shawnsdaddy** [comment]
有预测的，可能不太准
