### ISSUE TITLE
低优先回满就回去上班了

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#625]
最大组人数设为5的时候，4VIP+3低优先的分组 其中一个低优先回满心情就整组回去上班了，导致频繁上下班

**Comment by Shawnsdaddy** [comment]
log 给一下呗，还有排班表

**Comment by czt635** [comment]
[runtime2.log](https://github.com/user-attachments/files/16062815/runtime2.log)
[runtime1 (2).log](https://github.com/user-attachments/files/16062822/runtime1.2.log)
[runtime3.log](https://github.com/user-attachments/files/16062826/runtime3.log)

**Comment by Shawnsdaddy** [comment]
还有这问题嘛，没有的话close了
@czt635
