### ISSUE TITLE
大组低优先回满心情后就回去工作了

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#666]
宿舍不养闲人模式下 泰拉组低优先回满心情后就拖着心情没满的夜刀上班了
之前的版本没有这个问题 是最新版特意改成这样的 还是bug?

**Comment by Anyk00** [comment]
上个没问题的版本是哪个？新版似乎很多人反馈不养闲人失效。

**Comment by Shawnsdaddy** [comment]
no evidence
