### ISSUE TITLE
菲亚充能与休息撞车

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#681]
如果菲亚充能干员进宿舍与菲亚充能时间很近，先进宿舍后马上充能，充能后干员不会回去工作

**Comment by Shawnsdaddy** [comment]
logy有嘛

**Comment by czt635** [comment]
[Uploading runtime.log…]()
9月13日14点 到16点 看看是不是

**Comment by czt635** [comment]
> logy有嘛

[Uploading runtime.log…]()
9月13日14点 到16点 看看是不是

**Comment by czt635** [comment]
> logy有嘛

log不知道为什么 发不上来 发到频道log提交里面了

**Comment by Shawnsdaddy** [comment]
> 如果菲亚充能干员进宿舍与菲亚充能时间很近，先进宿舍后马上充能，充能后干员不会回去工作

具体写一下时间和任务呗，这样理解起来比较容易

**Comment by czt635** [comment]
[runtime(2).log](https://github.com/user-attachments/files/17686716/runtime.2.log)

**Comment by czt635** [comment]
> [runtime(2).log](https://github.com/user-attachments/files/17686716/runtime.2.log)
2024年11月9日
17:24 歌蕾蒂娅所在组进宿舍休息17:31（此时还未生成上班任务） 菲亚给歌蕾蒂娅充能 充能后歌蕾蒂娅所在组并未回去上班 而是继续在宿舍休息

**Comment by Shawnsdaddy** [comment]
> > [runtime(2).log](https://github.com/user-attachments/files/17686716/runtime.2.log)
> > 2024年11月9日
> > 17:24 歌蕾蒂娅所在组进宿舍休息17:31（此时还未生成上班任务） 菲亚给歌蕾蒂娅充能 充能后歌蕾蒂娅所在组并未回去上班 而是继续在宿舍休息

好好，了解了
