### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#684]
建议开始执行增加附表为ture启动，就是可以设置以某个（或者几个）附表为ture的状态开始执行

**Comment by Shawnsdaddy** [comment]
缓存所有数据应该能解决这个问题，等9.3吧

**Comment by czt635** [comment]
不是关闭后开启 而是首次开启就能设置附表为ture
因为有时候出现bug需要清空缓存 然后开启后附表没ture 排班就乱了

**Comment by Shawnsdaddy** [comment]
> 不是关闭后开启 而是首次开启就能设置附表为ture 因为有时候出现bug需要清空缓存 然后开启后附表没ture 排班就乱了



> 不是关闭后开启 而是首次开启就能设置附表为ture 因为有时候出现bug需要清空缓存 然后开启后附表没ture 排班就乱了

9.3改成了存在DB，只要你不手动移动干员位置。不需要清空缓存启动了

**Comment by Shawnsdaddy** [comment]
> 不是关闭后开启 而是首次开启就能设置附表为ture 因为有时候出现bug需要清空缓存 然后开启后附表没ture 排班就乱了



> 不是关闭后开启 而是首次开启就能设置附表为ture 因为有时候出现bug需要清空缓存 然后开启后附表没ture 排班就乱了

需要程序判断条件的问题，为什么需要人手工设置条件呢？只会带来更多问题
