### ISSUE TITLE
附表判定和生成排班表的顺序

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#686]
附表触发时机不管是任务开始还是上班结束，都是读取心情→生成排班表→判断附表→排班，这样即使判断附表为ture还是按主表排班

**Comment by czt635** [comment]
希望能修改成 读取心情→判断附表→生成排班表→排班

**Comment by Shawnsdaddy** [comment]
例子具体一点，不懂

时机设置对的话，
就是-> 读取心情→生成排班表→排班 -> 启动副表->生成副表上班 

时机不对的话就是
就是-> 读取心情→生成排班表→排班 -> >生成副表上班->启动副表->

**Comment by czt635** [comment]
前提 007深海 夕+重岳替换为替换组（没有令） 主表森蚺和歌蕾蒂娅一起下班 当森蚺心情高于戴菲恩 启动附表戴菲恩和歌蕾蒂娅一起下班 附表触发时机设置为上班结束（森蚺+歌蕾蒂娅上班结束）
但是当森蚺+歌蕾蒂娅上班结束后 →读取心情→启动附表→森蚺单独下班了

**Comment by czt635** [comment]
![plan](https://github.com/user-attachments/assets/a59c7914-17e8-476c-aff4-8b31f390c86a)

**Comment by Shawnsdaddy** [comment]
副表条件必须是实际基建状态，而不能是预判
