### ISSUE TITLE
mower进入死循环

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#690]
多次在访问好友的界面陷入死循环
![image](https://github.com/user-attachments/assets/250c8d47-f3a1-4cb8-9c0b-6de41e67e74f)
![image](https://github.com/user-attachments/assets/ff2c2104-e0f5-408f-839f-b09e4c7391bd)
[runtime.log](https://github.com/user-attachments/files/17054309/runtime.log)

**Comment by Franklee2333** [comment]
你这个是启动失败了，设置一下？
