### ISSUE TITLE
docker中无法正常构建image与使用，端口无法固定，log输出存在问题

### ISSUE THREAD

**Issue by 0O0o0oOoO00** [ArkMowers/arknights-mower#701]
![image](https://github.com/user-attachments/assets/a7cc69b9-81cb-4f6b-a667-9f3339115aee)

环境：
Ubuntu 22.04.4 LTS
![image](https://github.com/user-attachments/assets/5493c2c7-911a-4616-bc14-3ed0d79a8a2a)
![image](https://github.com/user-attachments/assets/925878d8-d114-405f-a12b-e1f8eb764ee2)

**Comment by Shawnsdaddy** [comment]
python 3.11 

你是不是版本不对？

**Comment by 0O0o0oOoO00** [comment]
dockerfile里不是安装的python3.8吗我看
https://github.com/ArkMowers/arknights-mower/blob/5be1769dd78052228109948b8ff780b32d2a4033/Dockerfile#L11-L15

而且后面也是python3.8设置的虚拟环境
https://github.com/ArkMowers/arknights-mower/blob/5be1769dd78052228109948b8ff780b32d2a4033/Dockerfile#L40

最后用3.8去安装的依赖
https://github.com/ArkMowers/arknights-mower/blob/5be1769dd78052228109948b8ff780b32d2a4033/Dockerfile#L44

**Comment by 0O0o0oOoO00** [comment]
将Dockerfile中所有的3.8改成3.11后可以构建成功

**Comment by 0O0o0oOoO00** [comment]
目前无法从外部访问，无法固定端口
![image](https://github.com/user-attachments/assets/b3dedf90-f1a2-4d29-afa5-8b3824e2ef72)
