### ISSUE TITLE
zhaozuohong的ssl证书过期了，mower一直卡在检查热更新资源，把mower的检查版本更新关了也没用

### ISSUE THREAD

**Issue by nailoy** [ArkMowers/arknights-mower#706]
10-30 16:43:38 检查热更新资源
10-30 16:43:39 程序出错--->HTTPSConnectionPool(host='mower.zhaozuohong.vip', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mower.zhaozuohong.vip'. (_ssl.c:1000)")))
10-30 16:43:39 SchedulerTask(time='2024-10-30 17:35:24.167980',task_plan={'room_1_1': ['但书', '龙舌兰', 'Current']},task_type=TaskTypes.RUN_ORDER,meta_data='room_1_1')||SchedulerTask(time='2024-10-30 19:24:15.392336',task_plan={'central': ['森蚺', 'Current', 'Current', 'Current', 'Current'], 'room_1_3': ['承曦格雷伊'], 'room_2_2': ['温蒂', '异客', '掠风']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm0,dorm3,dorm1,dorm2')||SchedulerTask(time='2024-10-30 19:37:29.293057',task_plan={'room_2_3': ['澄闪']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm5')||SchedulerTask(time='2024-10-31 03:31:58.537010',task_plan={},task_type=TaskTypes.FIAMMETTA,meta_data='')||SchedulerTask(time='2024-10-31 16:36:47.025501',task_plan={},task_type=TaskTypes.CLUE_PARTY,meta_data='')
10-30 16:43:39 检查热更新资源
10-30 16:43:39 程序出错--->HTTPSConnectionPool(host='mower.zhaozuohong.vip', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mower.zhaozuohong.vip'. (_ssl.c:1000)")))
10-30 16:43:39 SchedulerTask(time='2024-10-30 17:35:24.167980',task_plan={'room_1_1': ['但书', '龙舌兰', 'Current']},task_type=TaskTypes.RUN_ORDER,meta_data='room_1_1')||SchedulerTask(time='2024-10-30 19:24:15.392336',task_plan={'central': ['森蚺', 'Current', 'Current', 'Current', 'Current'], 'room_1_3': ['承曦格雷伊'], 'room_2_2': ['温蒂', '异客', '掠风']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm0,dorm3,dorm1,dorm2')||SchedulerTask(time='2024-10-30 19:37:29.293057',task_plan={'room_2_3': ['澄闪']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm5')||SchedulerTask(time='2024-10-31 03:31:58.537010',task_plan={},task_type=TaskTypes.FIAMMETTA,meta_data='')||SchedulerTask(time='2024-10-31 16:36:47.025501',task_plan={},task_type=TaskTypes.CLUE_PARTY,meta_data='')
10-30 16:43:39 检查热更新资源
10-30 16:43:40 程序出错--->HTTPSConnectionPool(host='mower.zhaozuohong.vip', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mower.zhaozuohong.vip'. (_ssl.c:1000)")))
10-30 16:43:40 SchedulerTask(time='2024-10-30 17:35:24.167980',task_plan={'room_1_1': ['但书', '龙舌兰', 'Current']},task_type=TaskTypes.RUN_ORDER,meta_data='room_1_1')||SchedulerTask(time='2024-10-30 19:24:15.392336',task_plan={'central': ['森蚺', 'Current', 'Current', 'Current', 'Current'], 'room_1_3': ['承曦格雷伊'], 'room_2_2': ['温蒂', '异客', '掠风']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm0,dorm3,dorm1,dorm2')||SchedulerTask(time='2024-10-30 19:37:29.293057',task_plan={'room_2_3': ['澄闪']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm5')||SchedulerTask(time='2024-10-31 03:31:58.537010',task_plan={},task_type=TaskTypes.FIAMMETTA,meta_data='')||SchedulerTask(time='2024-10-31 16:36:47.025501',task_plan={},task_type=TaskTypes.CLUE_PARTY,meta_data='')
10-30 16:43:40 检查热更新资源
10-30 16:43:41 程序出错--->HTTPSConnectionPool(host='mower.zhaozuohong.vip', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mower.zhaozuohong.vip'. (_ssl.c:1000)")))
10-30 16:43:41 SchedulerTask(time='2024-10-30 17:35:24.167980',task_plan={'room_1_1': ['但书', '龙舌兰', 'Current']},task_type=TaskTypes.RUN_ORDER,meta_data='room_1_1')||SchedulerTask(time='2024-10-30 19:24:15.392336',task_plan={'central': ['森蚺', 'Current', 'Current', 'Current', 'Current'], 'room_1_3': ['承曦格雷伊'], 'room_2_2': ['温蒂', '异客', '掠风']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm0,dorm3,dorm1,dorm2')||SchedulerTask(time='2024-10-30 19:37:29.293057',task_plan={'room_2_3': ['澄闪']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm5')||SchedulerTask(time='2024-10-31 03:31:58.537010',task_plan={},task_type=TaskTypes.FIAMMETTA,meta_data='')||SchedulerTask(time='2024-10-31 16:36:47.025501',task_plan={},task_type=TaskTypes.CLUE_PARTY,meta_data='')
10-30 16:43:41 检查热更新资源
10-30 16:43:41 程序出错--->HTTPSConnectionPool(host='mower.zhaozuohong.vip', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mower.zhaozuohong.vip'. (_ssl.c:1000)")))
10-30 16:43:41 SchedulerTask(time='2024-10-30 17:35:24.167980',task_plan={'room_1_1': ['但书', '龙舌兰', 'Current']},task_type=TaskTypes.RUN_ORDER,meta_data='room_1_1')||SchedulerTask(time='2024-10-30 19:24:15.392336',task_plan={'central': ['森蚺', 'Current', 'Current', 'Current', 'Current'], 'room_1_3': ['承曦格雷伊'], 'room_2_2': ['温蒂', '异客', '掠风']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm0,dorm3,dorm1,dorm2')||SchedulerTask(time='2024-10-30 19:37:29.293057',task_plan={'room_2_3': ['澄闪']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm5')||SchedulerTask(time='2024-10-31 03:31:58.537010',task_plan={},task_type=TaskTypes.FIAMMETTA,meta_data='')||SchedulerTask(time='2024-10-31 16:36:47.025501',task_plan={},task_type=TaskTypes.CLUE_PARTY,meta_data='')
10-30 16:43:41 检查热更新资源
10-30 16:43:42 程序出错--->HTTPSConnectionPool(host='mower.zhaozuohong.vip', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mower.zhaozuohong.vip'. (_ssl.c:1000)")))
10-30 16:43:42 SchedulerTask(time='2024-10-30 17:35:24.167980',task_plan={'room_1_1': ['但书', '龙舌兰', 'Current']},task_type=TaskTypes.RUN_ORDER,meta_data='room_1_1')||SchedulerTask(time='2024-10-30 19:24:15.392336',task_plan={'central': ['森蚺', 'Current', 'Current', 'Current', 'Current'], 'room_1_3': ['承曦格雷伊'], 'room_2_2': ['温蒂', '异客', '掠风']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm0,dorm3,dorm1,dorm2')||SchedulerTask(time='2024-10-30 19:37:29.293057',task_plan={'room_2_3': ['澄闪']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm5')||SchedulerTask(time='2024-10-31 03:31:58.537010',task_plan={},task_type=TaskTypes.FIAMMETTA,meta_data='')||SchedulerTask(time='2024-10-31 16:36:47.025501',task_plan={},task_type=TaskTypes.CLUE_PARTY,meta_data='')
10-30 16:43:42 检查热更新资源
10-30 16:43:43 程序出错--->HTTPSConnectionPool(host='mower.zhaozuohong.vip', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mower.zhaozuohong.vip'. (_ssl.c:1000)")))
10-30 16:43:43 SchedulerTask(time='2024-10-30 17:35:24.167980',task_plan={'room_1_1': ['但书', '龙舌兰', 'Current']},task_type=TaskTypes.RUN_ORDER,meta_data='room_1_1')||SchedulerTask(time='2024-10-30 19:24:15.392336',task_plan={'central': ['森蚺', 'Current', 'Current', 'Current', 'Current'], 'room_1_3': ['承曦格雷伊'], 'room_2_2': ['温蒂', '异客', '掠风']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm0,dorm3,dorm1,dorm2')||SchedulerTask(time='2024-10-30 19:37:29.293057',task_plan={'room_2_3': ['澄闪']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm5')||SchedulerTask(time='2024-10-31 03:31:58.537010',task_plan={},task_type=TaskTypes.FIAMMETTA,meta_data='')||SchedulerTask(time='2024-10-31 16:36:47.025501',task_plan={},task_type=TaskTypes.CLUE_PARTY,meta_data='')
10-30 16:43:43 检查热更新资源
10-30 16:43:43 程序出错--->HTTPSConnectionPool(host='mower.zhaozuohong.vip', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mower.zhaozuohong.vip'. (_ssl.c:1000)")))
10-30 16:43:43 SchedulerTask(time='2024-10-30 17:35:24.167980',task_plan={'room_1_1': ['但书', '龙舌兰', 'Current']},task_type=TaskTypes.RUN_ORDER,meta_data='room_1_1')||SchedulerTask(time='2024-10-30 19:24:15.392336',task_plan={'central': ['森蚺', 'Current', 'Current', 'Current', 'Current'], 'room_1_3': ['承曦格雷伊'], 'room_2_2': ['温蒂', '异客', '掠风']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm0,dorm3,dorm1,dorm2')||SchedulerTask(time='2024-10-30 19:37:29.293057',task_plan={'room_2_3': ['澄闪']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm5')||SchedulerTask(time='2024-10-31 03:31:58.537010',task_plan={},task_type=TaskTypes.FIAMMETTA,meta_data='')||SchedulerTask(time='2024-10-31 16:36:47.025501',task_plan={},task_type=TaskTypes.CLUE_PARTY,meta_data='')
10-30 16:43:43 检查热更新资源
10-30 16:43:44 程序出错--->HTTPSConnectionPool(host='mower.zhaozuohong.vip', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mower.zhaozuohong.vip'. (_ssl.c:1000)")))
10-30 16:43:44 SchedulerTask(time='2024-10-30 17:35:24.167980',task_plan={'room_1_1': ['但书', '龙舌兰', 'Current']},task_type=TaskTypes.RUN_ORDER,meta_data='room_1_1')||SchedulerTask(time='2024-10-30 19:24:15.392336',task_plan={'central': ['森蚺', 'Current', 'Current', 'Current', 'Current'], 'room_1_3': ['承曦格雷伊'], 'room_2_2': ['温蒂', '异客', '掠风']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm0,dorm3,dorm1,dorm2')||SchedulerTask(time='2024-10-30 19:37:29.293057',task_plan={'room_2_3': ['澄闪']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm5')||SchedulerTask(time='2024-10-31 03:31:58.537010',task_plan={},task_type=TaskTypes.FIAMMETTA,meta_data='')||SchedulerTask(time='2024-10-31 16:36:47.025501',task_plan={},task_type=TaskTypes.CLUE_PARTY,meta_data='')
10-30 16:43:44 检查热更新资源
10-30 16:43:45 程序出错--->HTTPSConnectionPool(host='mower.zhaozuohong.vip', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mower.zhaozuohong.vip'. (_ssl.c:1000)")))
10-30 16:43:45 SchedulerTask(time='2024-10-30 17:35:24.167980',task_plan={'room_1_1': ['但书', '龙舌兰', 'Current']},task_type=TaskTypes.RUN_ORDER,meta_data='room_1_1')||SchedulerTask(time='2024-10-30 19:24:15.392336',task_plan={'central': ['森蚺', 'Current', 'Current', 'Current', 'Current'], 'room_1_3': ['承曦格雷伊'], 'room_2_2': ['温蒂', '异客', '掠风']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm0,dorm3,dorm1,dorm2')||SchedulerTask(time='2024-10-30 19:37:29.293057',task_plan={'room_2_3': ['澄闪']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm5')||SchedulerTask(time='2024-10-31 03:31:58.537010',task_plan={},task_type=TaskTypes.FIAMMETTA,meta_data='')||SchedulerTask(time='2024-10-31 16:36:47.025501',task_plan={},task_type=TaskTypes.CLUE_PARTY,meta_data='')
10-30 16:43:45 检查热更新资源
10-30 16:43:45 程序出错--->HTTPSConnectionPool(host='mower.zhaozuohong.vip', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mower.zhaozuohong.vip'. (_ssl.c:1000)")))
10-30 16:43:45 SchedulerTask(time='2024-10-30 17:35:24.167980',task_plan={'room_1_1': ['但书', '龙舌兰', 'Current']},task_type=TaskTypes.RUN_ORDER,meta_data='room_1_1')||SchedulerTask(time='2024-10-30 19:24:15.392336',task_plan={'central': ['森蚺', 'Current', 'Current', 'Current', 'Current'], 'room_1_3': ['承曦格雷伊'], 'room_2_2': ['温蒂', '异客', '掠风']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm0,dorm3,dorm1,dorm2')||SchedulerTask(time='2024-10-30 19:37:29.293057',task_plan={'room_2_3': ['澄闪']},task_type=TaskTypes.SHIFT_ON,meta_data='dorm5')||SchedulerTask(time='2024-10-31 03:31:58.537010',task_plan={},task_type=TaskTypes.FIAMMETTA,meta_data='')||SchedulerTask(time='2024-10-31 16:36:47.025501',task_plan={},task_type=TaskTypes.CLUE_PARTY,meta_data='')

**Comment by Shawnsdaddy** [comment]
最新版在2024.11.1或者qq群内分享
