### ISSUE TITLE
建议启用附表之后重新生成上班任务

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#708]
建议启用附表 并且按附表上下班、纠错都完成后，增加一个清空上班任务重新生成上班任务的流程
适用情况：
我是赤金制造站：（（苍台、砾）、槐琥）；经验制造站：（稀音、红云、K200）,稀音休息的时候启用附表。变成赤金制造站：（（苍台、砾）、斑点）；经验制造站：（槐琥、断罪者、弑君者）（这么设置是因为这样斑点有35的效率 其他后补都只有30的效率）
但是如果槐琥进了宿舍，存在一个槐琥上班的任务，再启用附表后，槐琥虽然被强制再经验站上班了，但是上班任务还在，会导致上班任务后，槐琥回到赤金站，然后触发纠错，导致稀音提前回去上班
如果在附表启用后，增加一个清空上班任务重新生成上班任务的流程 ，就可以把槐琥上班的任务清空，就不会出现这个情况
![plan](https://github.com/user-attachments/assets/f61217da-7f49-4206-9d93-e74980b78539)

**Comment by Shawnsdaddy** [comment]
如果该附表没有自定义任务，则会自动加空任务

**Comment by czt635** [comment]
附表有让槐琥换一个制造站的自定义任务啊
