### ISSUE TITLE
maa调用错误

### ISSUE THREAD

**Issue by czt635** [ArkMowers/arknights-mower#711]
已按群公告替换msvcp140.dll版本，还是调用错误
maa版本v5.10.2-win-x64
mower版本12.1.1增量
[runtime.log](https://github.com/user-attachments/files/18031702/runtime.log)

**Comment by czt635** [comment]
Failed to load dynlib/dll 'None'. Most likely this dynlib/dll was not found when the application was frozen.

**Comment by Anyk00** [comment]
大更以后要重新删一遍dll文件

**Comment by Shawnsdaddy** [comment]
> > 大更以后要重新删一遍dll文件
> 
> 请教一下怎么删除

请注意留意Q群公告

**Comment by Anyk00** [comment]
就是按那个替换的方法，你可以选择替换也可以直接删掉
